<script setup lang="ts">
import { h, resolveComponent } from 'vue'
import type { TableColumn } from '@nuxt/ui'
const api=useGarmetixApi(); const auth=useAuth(); const workspace=useWorkspace(); const feedback=useUiFeedback(); const isAuthenticated=auth.isAuthenticated; const canEdit=auth.canEdit; const canDelete=auth.canDelete
const UButton=resolveComponent('UButton'); const rows=ref<any[]>([]); const categories=ref<any[]>([]); const search=ref(''); const loading=ref(false); const loadError=ref(''); const formOpen=ref(false); const saving=ref(false); const form=reactive<any>({id:'',companyId:'',name:'',categoryId:null})
const categoryOptions=computed(()=>categories.value.map((c:any)=>({label:c.name,value:c.id})))
const filteredRows=computed(()=>rows.value.filter((r:any)=>!search.value || [r.name,r.categoryName].some(v=>String(v||'').toLowerCase().includes(search.value.toLowerCase()))))
const columns:TableColumn<any>[]=[{accessorKey:'name',header:'Sub-category'},{accessorKey:'categoryName',header:'Category'},{id:'actions',header:'',cell:({row})=>h('div',{class:'flex justify-end gap-1'},[h(UButton,{icon:'i-lucide-pencil',label:'Edit',size:'sm',variant:'ghost',disabled:!canEdit.value,onClick:()=>startEdit(row.original)}),h(UButton,{icon:'i-lucide-trash-2',label:'Delete',size:'sm',variant:'ghost',color:'error',disabled:!canDelete.value,onClick:()=>removeRow(row.original)})])}]
async function refresh(){loading.value=true; loadError.value=''; try{const [catRows,subRows]=await Promise.all([api.list<any>('masters/product-categories'),api.list<any>('masters/product-subcategories')]); categories.value=catRows; rows.value=subRows.map((s:any)=>({...s,categoryName:catRows.find((c:any)=>c.id===s.categoryId)?.name||'-'}))}catch(e:any){loadError.value=e.message||'Sub-category load failed'; feedback.failed('Sub-category load failed',e)}finally{loading.value=false}}
function startCreate(){Object.assign(form,{id:'',companyId:workspace.companyId.value||'',name:'',categoryId:categories.value[0]?.id||null}); formOpen.value=true} function startEdit(row:any){Object.assign(form,{...row}); formOpen.value=true}
async function save(){saving.value=true; try{if(!form.companyId) throw new Error('Select company/workspace first.'); if(form.id) await api.update<any>('masters/product-subcategories',form.id,form); else await api.create<any>('masters/product-subcategories',form); feedback.saved('Sub-category saved'); formOpen.value=false; await refresh()}catch(e:any){feedback.failed('Sub-category save failed',e)}finally{saving.value=false}}
async function removeRow(row:any){if(!confirm(`Delete sub-category ${row.name}?`)) return; try{await api.remove('masters/product-subcategories',row.id); feedback.notify('Sub-category removed'); await refresh()}catch(e:any){feedback.failed('Sub-category delete failed',e)}}
onMounted(()=>{auth.restore(); refresh()})
</script><template><AuthScreen v-if="!isAuthenticated" @authenticated="refresh"/><AppShell v-else title="Product Sub-categories" @refresh="refresh" @workspace-change="refresh"><section class="planner-dashboard"><UiModulePageHeader title="Product Sub-category Master" description="Manage sub-category mapping under product categories." icon="i-lucide-list-tree" primary-label="New Sub-category" primary-icon="i-lucide-plus" @primary="startCreate"/><UiRegisterPanel title="Sub-categories" :loading="loading" :error="loadError" :empty="filteredRows.length===0" empty-title="No sub-categories" empty-description="Add a sub-category or change search." empty-icon="i-lucide-list-tree" @retry="refresh"><template #actions><UiCrudToolbar v-model:search="search" search-placeholder="Search sub-category/category" :loading="loading" create-label="New Sub-category" @refresh="refresh" @create="startCreate"/></template><div class="planner-table-wrap"><UTable :data="filteredRows" :columns="columns"/></div></UiRegisterPanel><UiFormSlideover v-model:open="formOpen" :title="form.id?'Edit Sub-category':'New Sub-category'" submit-label="Save Sub-category" :loading="saving" @submit="save"><UFormField label="Sub-category name" required><UInput v-model="form.name" required/></UFormField><UFormField label="Category"><USelect v-model="form.categoryId" :items="categoryOptions"/></UFormField></UiFormSlideover></section></AppShell></template>
