export const APP_VERSION = '4.12.69'
export const APP_STAGE = 'Stage 11D-154 Stock Operation Product Autocomplete'
export const APP_RELEASE_NAME = 'Stage 11D-154: Stock Operation Product Autocomplete'
export const APP_BUILD_DATE = '2026-07-03'
export const APP_BUILD_CODE = 'GARMETIX-11D154-20260703-4269'

export const APP_HIGHLIGHTS = [
  'Stage 11D-154 replaces Stock Operations product dropdowns with searchable autocomplete pickers across Adjustment, Transfer, Physical Count and Write-off tabs, including barcode/store/stock/MRP selection hints.',
  'Stage 11D-153 fixes the Financial Year Closeout metric DTO constructor mismatch, removes invalid StoreGroupId access from sale invoice closeout scope, and computes production go-live purchase paid evidence from PurchasePayment rows instead of a missing PurchaseInvoice.Paid field.',
  'Stage 11D-150 adds Production Host Build QA plus Purchase Return Advanced Settlement acceptance with formal supplier return, exact ITC reversal, debit-note settlement, refund bank proof and accounting audit evidence.',
  'Stage 11D-149 adds Final Owner Sign-off with Ready / Not Ready status, printable owner declaration, CSV sign-off evidence and signature-proof checklist.',
  'Stage 11D-148 adds Production Go-Live Master Acceptance with master setup, sales, purchase, stock, accounting, bank, return, payroll, FY-lock and backup/restore gate checks.',
  'Stage 11D-147 adds Owner Closeout Command Center with profit, stock valuation, customer dues, vendor payable, note control, bank settlement and journal-balance evidence in one CSV-ready dashboard.',
  'Stage 11D-146 adds Stock Valuation Closure with negative-stock, zero-cost, movement-proof and stock-type valuation evidence before month/FY close.',
  'Stage 11D-145 adds invoice-wise and item-wise Profit/Loss reporting using sale item revenue and linked stock-out cost evidence.',
  'Stage 11D-144 adds Bank Reconciliation / Payment Settlement Closure with Complete / Not Complete status, CSV evidence export, non-cash settlement rows, payment-mode summaries, bank-account evidence, bank transaction journal checks and statement-line reconciliation warnings.',
  'Stage 11D-143 adds a Financial Year Closeout Dashboard with Complete / Not Complete status, consolidated section matrix, GST/accounting checks, customer/vendor balances, payroll readiness, stock risk, FY lock evidence and CSV closeout export.',
  'Stage 11D-141 adds Vendor Payable / Purchase Settlement Reconciliation with Complete / Not Complete status, CSV evidence export, vendor master bill/paid checks, invoice status/payment-row checks, debit-note settlement checks, voucher/journal evidence and non-cash bank mapping validation.',
  'Stage 11D-140 adds Customer Dues / Credit Balance Reconciliation with Complete / Not Complete status, CSV evidence export, customer-wise due/advance/credit-note checks, non-cash advance bank mapping checks, closeout checklist and next-module handoff guidance.',
  'Stage 11D-139 adds a public Goods Return & Exchange Policy page, links it from digital invoice pages, and prints the policy URL/summary on invoice PDFs with no refund and credit-note validity guidance.',
  'Stage 11D-138 wraps acceptance, GST, backup and maintenance pages inside the main AppShell, keeps navigation/sidebar/header visible, carries the LX-310 CRLF bridge hotfix, and hardens Attendance Kiosk Monitor APIs against older live database schemas.',
  'Stage 11D-129 adds final Print/PDF closure status, CSV evidence export, core sale/purchase sample blocking, live-printer operator rules, closeout checklist and next-module handoff guidance.',
  'Stage 11D-128 adds Day Book CSV evidence export, print/save-PDF view, export closure card, 5,000-row export scope and stronger source-opening return hints with source ID/type/date anchors.',
  'Stage 11D-127 adds Accounting/GST post-import live validation with Complete / Not Complete status, CSV evidence, GST/payment summaries, journal checks, stock movement checks, purchase-import proof acceptance checks, closeout checklist and next-module handoff guidance.',
  'Stage 11D-126 adds Attendance/Payroll real-month validation with Complete / Not Complete status, blocking/warning issue list, employee-wise evidence table, CSV export, final closeout checklist, known limitations and next outside-module handoff guidance.',
  'Stage 11D-124 closes Purchase Import with a Complete / Not Complete status, final closeout checklist, visible known limitations and next outside-module handoff guidance.',
  'Stage 11D-123 adds purchase import correction/revision guidance, parser QA summaries, and backup/restore proof checklists for safer real-invoice acceptance.',
  'Stage 11D-121 makes sale invoice barcode visibility mandatory in receipt view and print/PDF output, and adds wrapped/collapsible invoice remarks in the sale invoice list.',
  'Stage 11D-118 adds public Privacy Policy and Terms of Usage pages for Meta/WhatsApp verification, fixes the /privcy spelling with a redirect to /privacy, and exposes both pages without login.',
  'Stage 11D-117 keeps the Meta Cloud API fixes and aligns invoice WhatsApp sends to the 4-variable Aadwika approved template: customer, invoice number, amount and public bill URL.',
  'Stage 11D-114 polishes Purchase Inward final QA with inward-date based register filtering, clearer inward/entry date columns, wider purchase receipt view, purchase deep-link aliases and Day Book-aware return from new/revised inward.',
  'Stage 11D-113 completes vendor payment final QA polish with view, edit, delete, direct payment deep-link opening and Day Book vendor-payment source links routed to the Vendor Payments page.',
  'Stage 11D-112 adds Back to Day Book return navigation on sale, purchase, voucher, cash voucher, vendor payment and accounting source pages while preserving the last Day Book date/type/search/page state.',
  'Stage 11D-111 remembers Day Book date/type/search/page while moving to source pages and widens the detail drawer with ID-first, relevant tabulated transaction fields instead of raw developer data.',
  'Stage 11D-108 restores the missing Day Book plus/New button with quick-create actions for sale, purchase, vendor payment, voucher and cash voucher, and fixes route/menu validation hygiene.',
  'Stage 11D-104 adds admin purchase/vendor payment reconciliation endpoints to report and repair vendor paid totals, purchase invoice payment status/mode, and stale voucher/accounting artifacts after vendor payment edit/delete.',
  'Stage 11D-103 hardens vendor payment edit/delete by recalculating vendor paid totals and purchase invoice status from active payment rows, clearing stale bank artifacts when payment mode changes to cash, and allowing payment reference/remark correction.',
  'Stage 11D-100 makes purchase inward date user-controlled on new/edit purchase inward and posts stock ledger/purchase payment dates from the selected inward date.',
  'Stage 11D-99 fixes historical Vyapar sale import stock posting by checking ledger availability on the sale date and creating controlled bridge stock before stock-out when enabled.',
  'Stage 11D-94 fixes deployed database drift by ensuring SalesInvoices.Remarks exists at startup and adds runtime repair scripts for sale list, replacement approval and Vyapar imported invoice endpoints.',
  'Stage 11D-93 adds Vyapar import batch history, admin-only batch undo/reversal, bulk barcode mapping upload, mismatch export workflow, and final approval before database posting.',
  'Stage 11D-91 adds Vyapar Sale Import runtime validation scripts, database safety checks, deployment smoke checks, import verification guidance and explicit next-stage tracking for batch undo and barcode mapping upload.',
  'Stage 11D-88 adds Vyapar Sale Import for Sale Report Excel files with backend preview, barcode/stock matching, missing-product review, optional product/stock bridge creation and confirm-to-database posting.',
  'Stage 11D-87 adds Product Master size-wise filtering, detected size display, and server-side size filtering for imported/split stock items.',
  'Stage 11D-83 adds Purchase Import Acceptance: final QA summary, posting report endpoint/page, readiness checklist, status-wise import health, protected proof storage visibility and recent batch diagnostics before moving outside purchase import.',
  'Stage 11D-82 adds Cash Details day reconciliation, CSV export, copy-as-verification, denomination breakdown and variance checks against Day Opening/Closing and petty cash sheet cash-in-hand.',
  'Stage 11D-81 links posted supplier invoice imports and purchase inwards directly to price-tag printing, supports route-based auto-loading into 50×30/50×25 tag pages, and adds reprint tag actions from purchase invoice list/receipt.',
  'Stage 11D-80 adds supplier invoice import storage summary: protected posted proof bytes, unposted OCR/proof storage, status-wise draft counts, and refreshable storage visibility on the import page.',
  'Stage 11D-77 adds purchase import posting QA: stricter gross/discount/taxable/grand-total reconciliation, size split templates, bulk similar-product scanning, and failed/rejected scanned-history cleanup while protecting posted proofs.',
  'Stage 11D-73 fixes the Tally/column purchase invoice parser publish error by initializing the multi-line header skip counter before table-header detection while keeping the v4.11.87 parser improvements intact.',
  'Stage 11D-70 adds supplier invoice review tools: draft health summary, bulk default copying, MRP fill, ignored-line restore, and duplicate barcode blocking before posting.',
  'Stage 11D-67 improves supplier invoice recognition with item-table detection, header/footer filtering, amount plausibility checks, and vendor-wise correction learning.',
  'Stage 11D-63 adds optional local OCR helpers for supplier invoice PDFs/images, stronger parser heuristics for HSN/qty/rate/GST/line totals, extracted text download and draft reparse usability.',
  'Stage 11D-62 improves supplier invoice import with GST inclusive/exclusive review, product matching, duplicate override audit and proof backup retention.',
  'Stage 11D-60 restores missing campaign WhatsApp helper methods so API publish succeeds after the Digital Bill permission and UI polish slice.',
  'Stage 11D-58 adds approved WhatsApp marketing-template campaign sending, production readiness checks, and Digital Bill CRM final acceptance page.',
  'Stage 11D-53 fixes Nuxt UI SelectItem runtime crashes by replacing empty-string store filter options with safe sentinel values in Digital Bill Ad Banners and Analytics pages.',
  'Stage 11D-52 adds the Digital Bill Activity drawer with customer opens, PDF downloads, review/social clicks, banner clicks, feedback submissions and WhatsApp delivery/read history.',
  'Stage 11D-51 activates Digital Bill ad banners, public banner click tracking, Meta WhatsApp webhook delivery/read status updates, and Digital Bill Analytics dashboard.',
  'Stage 11D-50 fixes Digital Bill manual generation so admin users can generate customer invoice links from either the sale invoice GUID or the visible invoice number such as S-20260625-0001.',
  'Stage 11D-48 adds WhatsApp provider settings, ManualOnly/MetaCloudApi dispatch, auto-send after sale finalization, resend/retry logs, and public DigitalBills__PublicBaseUrl support.',
  'Stage 11D-47 adds Digital Bill CRM MVP with secure public invoice links, PDF download, review/social settings, private feedback, public noindex invoice page, admin Digital Bills register, permissions, schema repair and roadmap docs.',
  'Stage 11D-46 adds a runtime validation runner for Docker build/up, API health, app-info version, web reachability, DB connectivity, sale payment mismatch checks, mixed-payment allocation review, invoice replacement readiness and Royalwood import validation hooks.',
  'Stage 11D-46 keeps v4.11.60 functional fixes intact and packages final deployment checks so post-deploy issues can be caught before store use.',
  'Stage 11D-45 fixes mixed cash/non-cash sale collection so petty cash/day closing uses InvoicePayments row splits, preserves payment split during revised invoice copy, and adds admin-only hard delete for already-cancelled sales invoices with linked-row cleanup.',
  'Sale invoice register now supports Today, Yesterday, This Month, Last Month, This Year, Month-Year and Custom date filters with server-side search/status filters and 25/50/100/200 page sizes.',
  'Stage 11D-43 fixes the API publish failure in InvoiceReplacementEndpoints by removing the invalid PurchaseInvoice.PaidAmount reference and keeping purchase replacement approval audit snapshots compatible with the current domain model.',
  'Invoice replacement pending sales now uses a safe fallback party name to remove the nullable PartyName warning during publish.',
  'Stage 11D-42 stores final PDF/print acceptance evidence in AuditLogEntries and expands Print Final Acceptance into sale/purchase A4/A5, large invoice, amount box, footer, signature and page-summary checks.',
  'Print Final Acceptance now has backend evidence history so final handover proof survives browser/device changes.',
  'Stage 11D-41 adds invoice replacement approval so revised sale/purchase invoices are linked to originals and old invoices are cancelled/reversed only after owner/admin approval.',
  'Invoice Replacement Approvals now shows pending revised invoices and an audit ledger for requested, approved, completed and failed replacement events.',
  'Stage 11D-40 hardens payroll finalization with one backend transaction for review approval, salary draft preparation, payslip generation, optional salary payment posting, payroll adjustment recovery and month locking.',
  'Stage 11D-38 adds multi-select bulk delete to Monthly Attendance, deleting selected employee/date daily attendance rows and linked punches with locked-month protection.',
  'Stage 11D-37 makes backup files portable: company/version/IST/sequence filenames, recursive backup-folder listing after redeploy, and restore support for copied backup files.',
  'Stage 11D-36 adds Admin-only JSON table export/import, JSON snapshot backup/restore, cascade row delete and table clear tools for early production data correction.',
  'Stage 11D-32 adds a final go-live drill combining Docker/API health, production import/GST validation, payroll readiness and the remaining manual UI checklist.',
  'Stage 11D-29 applies GSTIN state-code tax splitting for purchase and sale invoices and changes sales invoice numbering to StoreCode/YYYYMM/INV/series.',
  'Stage 11D-26 fixes attendance manual punch entry permission so Store Manager, HR, Payroll, PowerUser, and Admin roles with Attendance access can punch without requiring global edit permission.',
  'Stage 11D-24 adds a shift-aware employee and attendance import toolkit with employee-specific shift rules, IST punch generation, backup/restore and validation scripts.',
  'Stage 11D-21 fixes /api/vendors ambiguity and prevents schema repair from altering the PurchaseInvoiceItems compatibility view.',
  'Stage 11D-18 fixes A4/A5 purchase and sale PDF amount boxes so totals stay inside the page summary panel and do not overlap signatures/footer.',
  'Stage 11D-16 adds multi-page Tally-style A4/A5 purchase and sales invoice PDFs with page summary and final grand totals.',
  'Stage 11D-11 adds housekeeping double-shift handling, admin/owner timing correction for check-in/break/check-out, shift CRUD protection, restricted shift-rule management, and duplicate punch no-error handling.',
  'Stage 11D-10 adds employee/gender/category/department shift assignment rules, split-shift lunch breaks, Break Out/In punches, and session-based full/half-day calculation.',
  'Stage 11D-9 fixes backend publish failure by replacing Program.cs FindFirstValue extension calls with FindFirst()?.Value in the attendance sync helper.',
  'Stage 11D-3 changes the HR Attendance tab to current-month server-side pagination with month, year, employee and status filters.',
  'Stage 11C-2 adds face/liveness simulator and local/private external bridge proof checks with Message Logs and raw face payload blocking.',
  'Stage 11C adds a privacy-safe face liveness readiness contract with blocked raw payload fields, provider checklist and operator page.',
  'Stage 11B-10 adds Windows and Linux Mantra contract rehearsal drills for safe enroll and raw-response blocking.',
  'Stage 11B-9 adds a local Mantra mock service harness for safe adapter rehearsal before the official SDK/service is installed.',
  'Stage 11B-8 adds a configurable Mantra local-service adapter with localhost/private-LAN URL guards, response normalization and raw biometric field blocking.',
  'Stage 11B-7 marks Mantra as the selected fingerprint device target and wires bridge enroll results into biometric enrollment reference capture.',
  'Stage 11B-6 hardens biometric enrollment with explicit consent validation, safe template references, readable employee rows, revocation workflow and Message Logs.',
  'Stage 11B-5 adds configurable kiosk fingerprint punch enforcement with local bridge proof validation, operator UI and Message Logs for blocked punches.',
  'Stage 11B-4 adds a runnable local fingerprint bridge service template with simulator adapter, local/private caller guard and no raw biometric payload output.',
  'Stage 11B-3 adds a guarded external fingerprint bridge connector for localhost/private vendor bridges with sanitized Message Logs and raw biometric field blocking.',
  'Stage 11B-2 adds a fingerprint bridge simulator handshake for health, capture, identify and enroll with sanitized Message Logs and no biometric payload storage.',
  'Stage 11B adds a vendor-neutral fingerprint bridge contract, readiness page, adapter checklist and privacy guard before any real SDK integration.',
  'Stage 11A physical tablet rehearsal adds an operator checklist, evidence capture contract and pass/fail criteria before fingerprint hardware work.',
  'Stage 11A build hardening removes the MAUI MainPage startup warning and adds Android build, APK/AAB, advisory and hardware rehearsal visibility.',
  'Stage 11A adds the native MAUI Android Attendance Kiosk shell, SQLite pending punch queue and web status page for the mobile kiosk contract.',
  'Stage 10M adds a Production Rehearsal page and API for live-data run sheets, blocking checks, issue buckets and go/no-go evidence before Stage 11.',
  'Stage 10L adds a Production Support page and API for failed save, failed print, backup warning, email/share failure and Cloudflare or hosted API mismatch drills.',
  'Stage 10K adds a production operator acceptance page and API for daily store opening, billing, cash closing, purchase, accounting, HR/payroll, backup and support rehearsal.',
  'Import/Export CSV download and upload now use hosted-safe API URLs with sanitized CSV filenames.',
  'Salary payment slips now have a direct PDF download action with safe filenames for SPAY voucher numbers.',
  'Voucher PDF downloads now use the shared document helper so hosted deployments avoid localhost API URLs and keep cleaner error messages.',
  'Petty Cash PDF now paginates all A5 transaction-detail rows instead of truncating busy cash sheets.',
  'Sale invoice acceptance validation now protects the dedicated full-page invoice flow, draft recovery, compact controls, Manager fallback, payment safety and automatic first print.',
  'Dashboard shell now uses one main vertical scroller with stable panel scrollbars while preserving horizontal table scroll.',
  'Notifications now mark the badge read using the newest valid visible alert timestamp and route each alert to its related module.',
  'System Info now uses the compact module header pattern instead of the oversized dashboard hero.',
  'System Health now shows Oracle secondary sync readiness, direction, wallet, tenant/source and last success.',
  'Company page helper text now wraps cleanly while header actions remain grouped as usable controls.',
  'Sale invoices now recover the internal Manager salesman automatically when a store has no active salesman master.',
  'Stage 10J adds a real import/export engine for products, customers, vendors, stock opening, billing, purchase, HR, payroll, attendance, vouchers, petty cash and access.',
  'Stock Opening import adjusts store-wise stock ledgers to the uploaded opening quantity and records an auditable stock movement.',
  'Customer and vendor master import/export are now first-class modules with templates, validation, create/update behavior and error report download.',
  "Stage 10I makes Day Closing use today\'s Day Open opening balance for petty cash book cash instead of silently overriding it with previous closing.",
  "Stage 10I shows a warning when today\'s Day Open opening balance differs from the previous petty cash sheet closing balance.",
  'Store Operations now shows a Day Closing petty cash preview popup so calculated petty cash values can be reviewed and corrected before save.',
  'Stage 10H adds /runtime-diagnostics with safe database table probes for post-deployment bug triage.',
  'Runtime diagnostics lists important page/API contracts so frontend 500 errors can be traced to the exact backend endpoint.',
  'A host-level Stage 10H drill verifies the runtime diagnostics endpoints after Docker restart.',
  'Stage 10G verifies every concrete Nuxt page is discoverable from both modern and legacy sidebars.',
  'Sidebar now includes direct create links for New Sale Invoice, New Customer, New Debit Note and New Credit Note.',
  'Legacy sidebar now mirrors the modern navigation so deployments using DASHBOARD_SHELL=legacy do not hide Stage 9/10 pages.',
  'Stage 10 Complete adds barcode print final acceptance, GST/e-Invoice production readiness, Google Drive backup sync checks, and audit trail/change-history final acceptance.',
  'Stage 10C adds barcode print center APIs and barcode final acceptance page for product, stock and purchase inward label testing.',
  'Stage 10D adds GST/e-Invoice production readiness review without enabling live IRP posting until provider configuration is confirmed.',
  'Stage 10E adds Google Drive backup final acceptance and cloud backup configuration visibility.',
  'Stage 10F adds audit trail final acceptance for edit/delete history across invoices, vouchers, cash, HR, payroll and attendance.',
  'Stage 10A adds a consolidated Production Final Acceptance page and API for final production go-live checks.',
  'Runtime smoke now accepts current GARMETIX build-code families and no longer reports current releases as stale Stage 8 builds.',
  'Stage 10A host drill checks health, app-info, production readiness, runtime smoke, Today\'s dashboard and attendance final acceptance in one command.',
  "Dashboard section now includes a Today's page with sales, purchase, receipt, payment, expense, cash voucher and active employee attendance snapshots.",
  "Today's dashboard includes last-14-day sales, purchase and gross-margin line graph data for the selected workspace.",
  'Stage 9 Complete finishes Attendance Core through final acceptance: kiosk base, photo proof, review, payroll review, salary draft, salary slip generation, confirmed salary payment posting, and device bridge planning.',
  'Stage 9G can generate SalaryPayment records from attendance-generated payslips only after explicit confirmation.',
  'Stage 9H uses the existing audited SalaryPayment accounting workflow when confirmed payments are generated.',
  'Stage 9I keeps fingerprint device bridge integration-ready without enabling raw fingerprint storage or vendor matching.',
  'Stage 9J adds final acceptance visibility for completed attendance features and remaining future kiosk/biometric work.',
  'Stage 9F can generate final SalaryPaySlip records from ReadyForPayroll attendance salary drafts after explicit user confirmation.',
  'Salary payment creation and accounting voucher posting remain separate workflows and are not triggered by attendance salary slip generation.',
  'Stage 9E adds salary slip draft preview rows from reviewed attendance payroll review data without posting payroll, vouchers, or salary slips.',
  'Attendance salary draft preview can be rebuilt and marked ReadyForPayroll or OnHold, but remains PreviewOnly until a later approved package.',
  'Stage 9D adds attendance payroll review rows with payable days, deduction days, overtime minutes, lock visibility, and review status without posting payroll.',
  'Attendance payroll review can be rebuilt from monthly attendance summaries and marked Reviewed, ApprovedForPayroll, or OnHold.',
  'Monthly attendance generation now fully qualifies the legacy HRM Attendance entity to avoid namespace/type collision during Docker API publish.',
  'Stage 9C adds manager face photo proof review, approve/reject/flag workflow, regularization linkage, retention visibility, and audit-ready photo status.',
  'Kiosk API base includes device registration, heartbeat, employee lookup, punch and sync-pending endpoints for future Android/MAUI kiosk apps.',
  'Face attendance is limited to photo-proof path placeholders; real face recognition and liveness checks remain future packages.',
  'Fingerprint support is limited to enrollment/device bridge placeholders; no raw fingerprint image is stored.',
  'Payroll attendance summary is available for review only; automatic salary deduction/posting remains a later package.',
  'Employee save now avoids EF Core DefaultIfEmpty translation failures during PUT /api/employees.',
  'Deprecated lucide-vue-next dependency removed; Nuxt UI lucide icons remain through @iconify-json/lucide.',
  'HR schema repair now auto-adds missing Package 22/23 employee columns and the EmployeePayrollAdjustments table on existing PostgreSQL volumes.',
  'HR Employee Master now supports auto employee code, photo preview, document/bank fields, lifecycle status and printable ID-card readiness.',
  'HR Benefits adds salary advance, advance recovery, leave, bonus, leave encashment, PF and gratuity adjustment workflow for payroll.',
  'Payroll generation and payment preview now consider HR Benefits adjustments such as advances, bonus, PF and gratuity rows.',
  'License Activation now has a dedicated admin page for signed client license generation, activation and status review.',
  'The API includes HMAC-signed offline license keys, masked license status and optional operational API enforcement.',
  'Docker/env templates now include LICENSE_* settings plus a persistent /app/license activation volume.',
  'A host-level license acceptance drill verifies status, optional activation and protected API blocking behavior.',
  'Test Automation now includes LICENSE_SAAS_ACTIVATION so licensing remains part of production readiness.',
  'SMTP, print/PDF, backup/restore, permission, secret hygiene and Docker acceptance checks remain in the release manifest.'
]
