<script setup lang="ts">
import { h, resolveComponent } from 'vue'
import type { TableColumn } from '@nuxt/ui'
const api=useGarmetixApi(); const auth=useAuth(); const feedback=useUiFeedback(); const isAuthenticated=auth.isAuthenticated; const canEdit=auth.canEdit; const canDelete=auth.canDelete
const UButton=resolveComponent('UButton'); const rows=ref<any[]>([]); const vendors=ref<any[]>([]); const search=ref(''); const loading=ref(false); const loadError=ref(''); const formOpen=ref(false); const saving=ref(false); const noSupplierValue='__none__'; const form=reactive<any>({id:'',name:'',brandCode:'',supplierId:noSupplierValue})
const vendorOptions=computed(()=>[{label:'No supplier link',value:noSupplierValue},...vendors.value.map((v:any)=>({label:v.name,value:v.id}))])
const filteredRows=computed(()=>rows.value.filter((r:any)=>!search.value || [r.name,r.brandCode].some(v=>String(v||'').toLowerCase().includes(search.value.toLowerCase()))))
const columns:TableColumn<any>[]=[{accessorKey:'name',header:'Brand'},{accessorKey:'brandCode',header:'Code'},{accessorKey:'supplierName',header:'Supplier'},{id:'actions',header:'',cell:({row})=>h('div',{class:'flex justify-end gap-1'},[h(UButton,{icon:'i-lucide-pencil',label:'Edit',size:'sm',variant:'ghost',disabled:!canEdit.value,onClick:()=>startEdit(row.original)}),h(UButton,{icon:'i-lucide-trash-2',label:'Delete',size:'sm',variant:'ghost',color:'error',disabled:!canDelete.value,onClick:()=>removeRow(row.original)})])}]
async function refresh(){loading.value=true; loadError.value=''; try{const [brandRows,vendorRows]=await Promise.all([api.list<any>('masters/brands'),api.list<any>('vendors')]); vendors.value=vendorRows; rows.value=brandRows.map((b:any)=>({...b,supplierName:vendorRows.find((v:any)=>v.id===b.supplierId)?.name||'-'}))}catch(e:any){loadError.value=e.message||'Brand load failed'; feedback.failed('Brand load failed',e)}finally{loading.value=false}}
function startCreate(){Object.assign(form,{id:'',name:'',brandCode:'',supplierId:noSupplierValue}); formOpen.value=true} function startEdit(row:any){Object.assign(form,{...row,supplierId:row.supplierId||noSupplierValue}); formOpen.value=true}
async function save(){saving.value=true; try{const payload={...form,supplierId:form.supplierId===noSupplierValue?null:form.supplierId}; if(form.id) await api.update<any>('masters/brands',form.id,payload); else await api.create<any>('masters/brands',payload); feedback.saved('Brand saved'); formOpen.value=false; await refresh()}catch(e:any){feedback.failed('Brand save failed',e)}finally{saving.value=false}}
async function removeRow(row:any){if(!confirm(`Delete brand ${row.name}?`)) return; try{await api.remove('masters/brands',row.id); feedback.notify('Brand removed'); await refresh()}catch(e:any){feedback.failed('Brand delete failed',e)}}
onMounted(()=>{auth.restore(); refresh()})
</script><template><AuthScreen v-if="!isAuthenticated" @authenticated="refresh"/><AppShell v-else title="Brands" @refresh="refresh"><section class="planner-dashboard"><UiModulePageHeader title="Brand Master" description="Add, edit and delete brand names used in product details and imports." icon="i-lucide-tags" primary-label="New Brand" primary-icon="i-lucide-plus" @primary="startCreate"/><UiRegisterPanel title="Brands" :loading="loading" :error="loadError" :empty="filteredRows.length===0" empty-title="No brands" empty-description="Add a brand or change search." empty-icon="i-lucide-tags" @retry="refresh"><template #actions><UiCrudToolbar v-model:search="search" search-placeholder="Search brand/code" :loading="loading" create-label="New Brand" @refresh="refresh" @create="startCreate"/></template><div class="planner-table-wrap"><UTable :data="filteredRows" :columns="columns"/></div></UiRegisterPanel><UiFormSlideover v-model:open="formOpen" :title="form.id?'Edit Brand':'New Brand'" submit-label="Save Brand" :loading="saving" @submit="save"><UFormField label="Brand name" required><UInput v-model="form.name" required/></UFormField><UFormField label="Brand code"><UInput v-model="form.brandCode"/></UFormField><UFormField label="Supplier"><USelect v-model="form.supplierId" :items="vendorOptions"/></UFormField></UiFormSlideover></section></AppShell></template>
