using System.Diagnostics;
using System.Text;
using Garmetix.Api.Auth;
using Garmetix.Core.Models.Configuration;
using Garmetix.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;

namespace Garmetix.Api.Configuration;

public sealed record ConfigEntryDto(
    Guid Id,
    string Key,
    string Category,
    string? DisplayName,
    string? Description,
    bool IsSecret,
    bool HasValue,
    string? DisplayValue,
    string? EnvVarName,
    bool WriteToApiEnv,
    DateTime? LastAppliedAt,
    DateTime? UpdatedAt,
    string? UpdatedByUserName);

public sealed record ConfigEntryUpdateRequest(string? Value, bool Clear = false);

public sealed record ConfigWriteToDiskResultDto(bool Success, string Message, int EntriesWritten, string? StagedAt);

public sealed record ConfigServiceActionResultDto(bool Success, string Message, string? Output);

/// <summary>
/// Configuration page backend - app owner/developer surface. Manages the env-var-backed runtime
/// settings previously only editable by hand-editing files on disk. Values are staged in
/// garmetix_config_db (encrypted at rest for secrets) until explicitly written to disk; the
/// actually-running API only picks up a change after write-to-disk + restart, both explicit,
/// separate actions - nothing here silently changes what the live process is doing.
/// </summary>
public static class ConfigurationEndpoints
{
    public static RouteGroupBuilder MapConfigurationEndpoints(this WebApplication app)
    {
        var group = app.MapGroup("/api/admin/configuration")
            .WithTags("Admin Configuration")
            .RequireAuthorization(GarmetixPolicies.Admin);

        group.MapGet("/", ListAsync);
        group.MapPut("/{key}", UpdateAsync);
        group.MapPost("/write-to-disk", WriteToDiskAsync);
        group.MapPost("/restart-service", RestartServiceAsync);
        group.MapPost("/write-and-restart", WriteAndRestartAsync);
        group.MapGet("/service-status", GetServiceStatusAsync);

        return group;
    }

    private static async Task<IResult> ListAsync(GarmetixConfigDbContext db, ConfigCredentialProtector protector, CancellationToken cancellationToken)
    {
        var entries = await db.ConfigEntries.AsNoTracking()
            .Where(e => e.Scope == ConfigScope.Configuration)
            .OrderBy(e => e.Category).ThenBy(e => e.DisplayName ?? e.Key)
            .ToListAsync(cancellationToken);

        return Results.Ok(entries.Select(e => ToDto(e, protector)).ToList());
    }

    private static async Task<IResult> UpdateAsync(string key, ConfigEntryUpdateRequest request, HttpContext context, GarmetixConfigDbContext db, ConfigCredentialProtector protector, CancellationToken cancellationToken)
    {
        var entry = await db.ConfigEntries.FirstOrDefaultAsync(e => e.Key == key && e.Scope == ConfigScope.Configuration, cancellationToken);
        if (entry is null)
        {
            return Results.NotFound(new { message = $"Unknown configuration key '{key}'." });
        }

        if (request.Clear)
        {
            entry.PlainValue = null;
            entry.EncryptedValue = null;
        }
        else if (!string.IsNullOrEmpty(request.Value))
        {
            if (entry.IsSecret)
            {
                entry.EncryptedValue = protector.Protect(request.Value);
                entry.PlainValue = null;
            }
            else
            {
                entry.PlainValue = request.Value;
                entry.EncryptedValue = null;
            }
        }

        entry.UpdatedAt = DateTime.UtcNow;
        entry.UpdatedByUserName = context.User.Identity?.Name;
        await db.SaveChangesAsync(cancellationToken);

        return Results.Ok(ToDto(entry, protector));
    }

    private static async Task<IResult> WriteToDiskAsync(GarmetixConfigDbContext db, ConfigCredentialProtector protector, IConfiguration configuration, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("ConfigurationWriteToDisk");
        var stagingDir = configuration["Config:StagingDirectory"];
        if (string.IsNullOrWhiteSpace(stagingDir))
        {
            return Results.Ok(new ConfigWriteToDiskResultDto(false, "Config:StagingDirectory is not configured on this environment - write-to-disk is only available on the deployed SRP host.", 0, null));
        }

        var entries = await db.ConfigEntries
            .Where(e => e.Scope == ConfigScope.Configuration && e.WriteToApiEnv)
            .ToListAsync(cancellationToken);

        var withValues = entries.Where(e => HasValue(e)).ToList();

        var builder = new StringBuilder();
        builder.AppendLine("# Generated by the Garmetix Configuration page - do not hand-edit, changes will be");
        builder.AppendLine("# overwritten on the next write-to-disk. Edit via /admin/configuration instead.");
        builder.AppendLine($"# Generated at {DateTime.UtcNow:O} UTC");
        foreach (var entry in withValues.OrderBy(e => e.EnvVarName))
        {
            var value = entry.IsSecret ? protector.Unprotect(entry.EncryptedValue) : entry.PlainValue;
            if (value is null)
            {
                continue;
            }

            builder.AppendLine($"{entry.EnvVarName}={value}");
        }

        string stagedPath;
        try
        {
            Directory.CreateDirectory(stagingDir);
            stagedPath = Path.Combine(stagingDir, "srp-api.env.staged");
            await File.WriteAllTextAsync(stagedPath, builder.ToString(), cancellationToken);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to write staged config file.");
            return Results.Ok(new ConfigWriteToDiskResultDto(false, $"Could not write the staged file: {ex.Message}", 0, null));
        }

        var applyScript = configuration["Config:ApplyScriptPath"] ?? "/usr/local/bin/garmetix-apply-config.sh";
        var result = await RunSudoCommandAsync("sudo", applyScript, logger, cancellationToken);
        if (!result.Success)
        {
            return Results.Ok(new ConfigWriteToDiskResultDto(false, $"Staged file written, but applying it failed: {result.Message}", withValues.Count, stagedPath));
        }

        var now = DateTime.UtcNow;
        foreach (var entry in withValues)
        {
            entry.LastAppliedAt = now;
        }
        await db.SaveChangesAsync(cancellationToken);

        return Results.Ok(new ConfigWriteToDiskResultDto(true, $"Wrote {withValues.Count} value(s) to /etc/garmetix/srp-api.env. Restart the service (or use Write & Restart) for the running process to pick them up.", withValues.Count, stagedPath));
    }

    private static async Task<IResult> RestartServiceAsync(IConfiguration configuration, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("ConfigurationRestartService");
        var serviceName = configuration["Config:ApiServiceName"] ?? "garmetix-srp-api.service";
        var result = await RunSudoCommandAsync("sudo", $"systemctl restart {serviceName}", logger, cancellationToken);
        return Results.Ok(new ConfigServiceActionResultDto(result.Success, result.Message, result.Output));
    }

    private static async Task<IResult> WriteAndRestartAsync(GarmetixConfigDbContext db, ConfigCredentialProtector protector, IConfiguration configuration, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
    {
        var writeResult = await WriteToDiskAsync(db, protector, configuration, loggerFactory, cancellationToken);
        if (writeResult is not Microsoft.AspNetCore.Http.HttpResults.Ok<ConfigWriteToDiskResultDto> okResult || !okResult.Value!.Success)
        {
            return writeResult;
        }

        var logger = loggerFactory.CreateLogger("ConfigurationRestartService");
        var serviceName = configuration["Config:ApiServiceName"] ?? "garmetix-srp-api.service";
        var restartResult = await RunSudoCommandAsync("sudo", $"systemctl restart {serviceName}", logger, cancellationToken);

        return Results.Ok(new
        {
            write = okResult.Value,
            restart = new ConfigServiceActionResultDto(restartResult.Success, restartResult.Message, restartResult.Output)
        });
    }

    private static async Task<IResult> GetServiceStatusAsync(IConfiguration configuration, ILoggerFactory loggerFactory, CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("ConfigurationServiceStatus");
        var serviceName = configuration["Config:ApiServiceName"] ?? "garmetix-srp-api.service";
        var result = await RunSudoCommandAsync("sudo", $"systemctl is-active {serviceName}", logger, cancellationToken);
        return Results.Ok(new ConfigServiceActionResultDto(result.Success, result.Message, result.Output));
    }

    private static async Task<(bool Success, string Message, string? Output)> RunSudoCommandAsync(string fileName, string arguments, ILogger logger, CancellationToken cancellationToken)
    {
        if (!OperatingSystem.IsLinux())
        {
            return (false, "This action is only available on the deployed Linux SRP host.", null);
        }

        try
        {
            var psi = new ProcessStartInfo
            {
                FileName = "/usr/bin/sudo",
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };
            foreach (var part in arguments.Split(' ', StringSplitOptions.RemoveEmptyEntries))
            {
                psi.ArgumentList.Add(part);
            }

            using var process = Process.Start(psi);
            if (process is null)
            {
                return (false, "Could not start the sudo process.", null);
            }

            var stdout = await process.StandardOutput.ReadToEndAsync(cancellationToken);
            var stderr = await process.StandardError.ReadToEndAsync(cancellationToken);
            await process.WaitForExitAsync(cancellationToken);

            var output = string.Join('\n', new[] { stdout, stderr }.Where(s => !string.IsNullOrWhiteSpace(s)));
            if (process.ExitCode != 0)
            {
                logger.LogWarning("sudo {Arguments} exited {Code}: {Output}", arguments, process.ExitCode, output);
                return (false, $"Command exited with code {process.ExitCode}.", output);
            }

            return (true, "Command completed successfully.", output);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to run sudo command: {Arguments}", arguments);
            return (false, ex.Message, null);
        }
    }

    private static bool HasValue(ConfigEntry entry) => entry.IsSecret ? !string.IsNullOrEmpty(entry.EncryptedValue) : !string.IsNullOrEmpty(entry.PlainValue);

    private static ConfigEntryDto ToDto(ConfigEntry entry, ConfigCredentialProtector protector)
    {
        var hasValue = HasValue(entry);
        string? displayValue = null;
        if (hasValue)
        {
            if (entry.IsSecret)
            {
                var decrypted = protector.Unprotect(entry.EncryptedValue);
                displayValue = decrypted is not null ? ConfigCredentialProtector.Mask(decrypted) : "(unreadable - re-enter)";
            }
            else
            {
                displayValue = entry.PlainValue;
            }
        }

        return new ConfigEntryDto(
            entry.Id,
            entry.Key,
            entry.Category,
            entry.DisplayName,
            entry.Description,
            entry.IsSecret,
            hasValue,
            displayValue,
            entry.EnvVarName,
            entry.WriteToApiEnv,
            entry.LastAppliedAt,
            entry.UpdatedAt,
            entry.UpdatedByUserName);
    }
}
