export const APP_VERSION = '4.7.2'
export const APP_STAGE = 'Stage 8H Package 3 Purchase and Voucher Crash Hotfix'
export const APP_RELEASE_NAME = 'Post-Go-Live Acceptance Stabilization'
export const APP_BUILD_DATE = '2026-06-17'
export const APP_BUILD_CODE = 'GARMETIX-8H-20260617-4720'

export const APP_HIGHLIGHTS = [
  'Final go-live acceptance checklist and role matrix are included for admin sign-off before production cutover.',
  'Stage 8G completion script runs security, backup, SMTP, GSTIN, Oracle sync, and Docker readiness checks from one command.',
  'Oracle Cloud sync readiness now checks wallet/TNS paths, external-app event review, auto-apply policy and dead-letter monitoring.',
  'Backup Maintenance now validates Google Drive off-site backup configuration and supports uploading verified local backups to Drive.',
  'Mac mini scripts now check Google Drive service-account JSON, folder id and off-site backup readiness before go-live.',
  'Backup Maintenance Center now checks recent backup age, disk space, directory write access, checksum coverage, manifest coverage and stale restore temp files.',
  'Backup cleanup can remove orphan checksum/manifest sidecars and temporary restore upload files without deleting valid backup dumps.',
  'Backup verification can now run across all local backup files so admins can confirm restore safety before power failure or production cutover.',
  'Linux/WSL scripts now include backup maintenance and direct PostgreSQL backup helpers for Mac mini operations.',
  'Automated backend, frontend and production smoke-test scripts now ship with the release package.',
  'The API exposes a test-automation manifest and runtime smoke endpoint for deployment validation.',
  'Frontend smoke checks verify the public login page and proxied app-info endpoint without a browser driver.',
  'Linux, WSL and Windows test runners can execute backend unit tests, Nuxt build checks and optional Docker health checks.',
  'Persistent audit logs now capture create, update and delete operations from DbContext SaveChanges with actor, route, trace id and module classification.',
  'Audit detail now shows before/after field values and changed-field counts while excluding sensitive password, token, API key and secret fields.',
  'The Audit screen now reads real AuditLogEntries first, with legacy CreatedAt/UpdatedAt fallback for older rows before audit capture begins.',
  'Tailoring and alteration orders now follow order-delivery-invoice-payment SOP with delivery schedule, pending, delivered, invoiced, paid and completed status tracking.',
  'Readymade garment alteration can be assigned to tailoring vendors with customer-chargeable, in-house expense, or complimentary cost responsibility.',
  'Tailoring service items are reusable in orders and service invoice conversion, with default customer rate, vendor rate, HSN/SAC and active status.',
  'Customer receipts and vendor payments are linked back to the tailoring order so order history, balances and profit impact remain visible.',
  'Business dashboard now shows customer dues, vendor dues, cash/payment summaries and store-group comparison views.',
  'Payment-mode summary separates sales collections, purchase payments, voucher receipts and voucher payments for the selected period.',
  'Store-group comparison now combines sales, purchase, due balances, cash in/out and stock value in one executive view.',
  'Party and bank-account ledger synchronization now has a health check and one-click repair workflow in Accounting.',
  'Party ledger links are protected from missing ledgers, wrong company links, shared party ledgers, non-party ledgers and wrong ledger types.',
  'Bank account ledgers are validated for missing links, wrong company/type links, shared bank ledgers and name drift before posting.',
  'Financial Year Locks now protect closed periods from back-dated sales, purchase, inventory, GST and accounting edits.',
  'Journal validation checks expose unbalanced entries, missing lines, negative amounts and debit/credit misuse before period close.',
  'The Mac mini deployment config now keeps RESET_DATABASE_ON_DEPLOY=false by default to prevent accidental PostgreSQL volume deletion.',
  'Fresh production installs now create one clean schema baseline from the current DbContext model instead of replaying historical branch migrations.',
  'Deployment supports a one-time PostgreSQL volume reset for failed test installs or new-server clean starts.',
  'Sales return invoices now carry a valid salesman reference from the original bill or active store fallback, preventing FK save failures.',
  'Sales exchange replacement invoices and billing imports now also avoid blank salesman foreign keys.',
  'Sales split payments now post separate settlement ledger and customer-credit rows for every collected payment line.',
  'Cash, bank, cheque, card, UPI, credit note, advance, store-credit and loyalty rows are routed to their own settlement ledgers instead of one mixed-payment ledger.',
  'Invoice payment rows now retain a structured payment-details JSON snapshot with mode, account, reference, gateway, cheque, card, UPI and adjustment metadata.',
  'Duplicate use of the same advance receipt, credit note, store credit or loyalty redemption is rejected before balances are changed.',
  'Nuxt font resolution now runs in local/no-provider mode so offline builds no longer depend on external font metadata.',
  'Owner and Admin users can move eligible cash records between Off Book Cash Vouchers and regular accounting vouchers without duplicating the amount.',
  'Every conversion retains source and destination numbers, direction, amount, reason, operator and timestamp in an immutable audit history.',
  'Moving a regular cash voucher Off Book removes its journal postings and preserves the original source as an audit-only record.',
  'Sales Invoice creation now uses a stable full page with draft recovery, mobile customer lookup, contextual payments, rounded totals and automatic print after save.',
  'Billing create, cancellation, return and exchange transactions now run through the PostgreSQL retry execution strategy.',
  'B2B interstate GST is derived from supplier and customer GSTIN state codes, with IGST applied to interstate GST supplies.',
  'Concurrent document numbering now requires an explicit transaction and is protected by both PostgreSQL advisory locking and one active sequence-row invariant.',
  'Stock transfers acquire source and destination locks in deterministic order before reading available quantity.',
  'New regular-stock outflows cannot create or deepen negative stock, while legacy negative history remains replayable and can be repaired by inward corrections.',
  'PostgreSQL-backed tests now verify concurrent numbering, stock-lock blocking and transaction ownership against the production database engine.',
  'The sidebar footer again presents Status above Notifications as two full-width vertical actions.',
  'Inventory now includes a dedicated Stock Reports workspace for receipt-age indicators, configurable low-stock risk, weighted-average valuation and ledger reconciliation.',
  'Stock report age bands cover 0-30, 31-60, 61-90, 91-180 and 180+ days, plus no-receipt-history and out-of-stock states.',
  'Stock Reports exposes Critical, Low, Watch and Healthy risk bands, pending stock-accounting documents, searchable filters and CSV export.',
  'Ledger quantity and average cost are compared with the operational stock projection so rebuild mismatches remain visible by product and store.',
  'Stock excess, shortage, write-off and inter-store transfer documents now post balanced double-entry accounting at weighted-average cost.',
  'Store-wise Stock-in-Hand ledgers are created internally, with stock gains in Indirect Income and shortages/write-offs in Indirect Expenses.',
  'Stock Operations now includes a dedicated Write-off workflow with StoreCode/YYYYMM/WO/series numbering and linked movement and journal audit.',
  'Formal stock-operation documents now show Posted, Not Required or Pending accounting status and their linked journal number.',
  'Status and Notifications are available as separate vertical actions in the sidebar footer.',
  'Regular stock movements now form the authoritative quantity and inventory-cost ledger, while Stock remains a rebuildable operational projection.',
  'Weighted-average valuation records running quantity, average cost, inventory value and cost impact for every regular stock movement.',
  'The Stock Operations workspace now includes valuation, projection reconciliation and movement running balances.',
  'Stock adjustments, transfers and physical counts now create formal header and item documents with immutable product, store, quantity and value snapshots.',
  'Every posted stock-operation document links its movement-ledger rows and uses server-owned StoreCode/YYYYMM/ADJ, ST or PHY numbering.',
  'The Stock Operations workspace now includes a searchable document register, operation filter, wide audit detail and direct QR download.',
  'Universal document scanning now opens permitted stock-operation details by stable QR token or document number.',
  'Purchase returns now persist an immutable ITC reversal row for every returned item, including HSN and exact CGST, SGST and IGST values.',
  'Purchase return details now reconcile the return header, item snapshots, stock movement, debit note, Input GST journal and settlement state.',
  'Full purchase cancellations use the same item-level ITC reversal and reconciliation links as partial returns.',
  'The dashboard shell now has one header bar, one collapse control, one account menu and notifications in the sidebar footer.',
  'Vendor debit notes can now be allocated across one or more outstanding purchase invoices without duplicating their accounting journal.',
  'Actual supplier refunds create receipt vouchers and balanced cash or bank entries linked to the vendor, return, debit note, journal and bank transaction.',
  'Vendor settlements support adjustment-only, refund-only and mixed workflows with server-owned StoreCode/YYYYMM/VSET/series numbering.',
  'The dedicated Vendor Settlements workspace shows open debit-note credit, invoice allocation, refund receipt, settlement history and audit links.',
  'Non-cash vendor refunds require a receiving bank account, while generated refund vouchers use StoreCode/YYYYMM/VREF/series numbering and printable QR receipts.',
  'Purchase returns now generate colored A4 or A5 Purchase Return and Debit Note PDFs containing every returned item and exact GST reversal totals.',
  'Each purchase-return document carries a stable QR code that opens the permitted return detail from Document Scanner.',
  'New returns open their first print automatically, while print count, reprint state, and last print time remain auditable.',
  'The Purchase Return register now filters print state and provides direct print, reprint, download, and detail actions.',
  'Purchase returns now persist formal return headers and immutable item-level product, HSN, GST, quantity, rate, vendor and original-purchase snapshots.',
  'New purchase return numbers use a server-owned StoreCode/YYYYMM/PR/series sequence.',
  'Partial returns and full purchase cancellations now link stock movements and debit notes to the formal return document.',
  'The Purchase Return workspace now includes a searchable return register and snapshot detail view.',
  'Legacy stock-movement-only purchase returns remain included when calculating returnable quantities.',
  'The dashboard shell now provides a role-filtered notification and quick-action menu in the topbar and sidebar.',
  'Business notifications expose friendly summaries and permitted destinations without stack traces, payloads or runtime noise.',
  'Mobile navigation closes after route changes, while collapsed-sidebar preference persists for each browser.',
  'Topbar, footer, command palette and navigation actions now share the same route permission rules.',
  'One server-owned permission matrix now drives Admin, entry, edit, delete and operational module authorization.',
  'The Access workspace displays the effective role matrix returned by the API.',
  'Store Manager retains store-module view and entry access without Admin, global edit or delete rights.',
  'Dedicated HR and Payroll roles open only their assigned people module and land there after login.',
  'Automated role tests cover Owner, Admin, Power User, Accountant, Store Manager, Salesman, HR and Payroll permissions.',
  'User activation, deactivation, role assignment, password administration and deletion are now explicit audited workflows.',
  'Inactive users are denied at login and immediately blocked from authenticated API requests.',
  'Admin access is derived from the Admin role and can no longer be enabled through a separate user-facing flag.',
  'Administrative password resets use a dedicated endpoint and revoke outstanding reset tokens.',
  'The last active admin and the currently signed-in account are protected from accidental deactivation or deletion.',
  'The Stage 8A page audit queue is complete across operational, administration, maintenance, profile and help workspaces.',
  'GST Returns now preserves local invoice and accounting dates and retains setup, draft and review failures with direct retry actions.',
  'Profile, About Garmetix, Contact Us and Help and FAQ now use consistent headers, loading states and business-facing guidance.',
  'FAQ category filtering now uses a safe internal all-value sentinel instead of an invalid empty selector value.',
  'Production Readiness, Release Stabilization, Data Consistency and Oracle Sync now retain load failures with direct retry actions.',
  'Maintenance workspaces now use shared page headers, loading skeletons, responsive data surfaces and clearer operational copy.',
  'Oracle Sync selectors use safe internal all-value sentinels and no longer create invalid empty SelectItem values.',
  'Company Setup and Roles and Users now use retryable registers, responsive tables and wide modal workspaces.',
  'Company, store-group and store dates preserve the selected local calendar date without UTC conversion.',
  'Company Onboarding and AF/SS Defaults now provide retained load failures, retry actions and responsive loading states.',
  'Internal migration, source-file and legacy implementation notes are no longer exposed on Admin business pages.',
  'Cash Voucher register now retains load failures with direct retry behavior and a voucher-type filter.',
  'Cash Voucher create and edit dates now preserve the selected local calendar date without UTC conversion.',
  'Cash Voucher entry remains a wide workspace and continues to stay completely outside ledgers, journals, banks and regular vouchers.',
  'Browser console errors and warnings are now persisted in Message Logs with page context.',
  'Product Master create and edit transactions now run inside the configured PostgreSQL retry execution strategy.',
  'Unhandled API exceptions are saved with trace and stack details while users receive a safe operation reference.',
  'Failed API responses and successful state-changing API requests are persisted automatically in Message Logs.',
  'Frontend notifications, action failures, Vue errors, browser errors and unhandled promise rejections are persisted.',
  'Sensitive tokens, passwords, authorization values and secrets are redacted from frontend diagnostics.',
  'Reports Center, GST Reports, Import Export, Audit Trail and Message Logs now use consistent retryable register states.',
  'Reports Center date defaults preserve the local Indian calendar date instead of converting through UTC.',
  'Report, audit and data-operation failures remain visible with a direct retry action.',
  'Large report tables stay inside responsive scroll containers while actions wrap across smaller screens.',
  'Message Logs use compact operational panels and keep technical details in expandable sections.',
  'Party and bank-account ledgers are now created and linked only by the accounting service.',
  'Accounting entry forms use wide workspaces and retain retryable register errors.',
  'Bank transactions expose the contra ledger while resolving party linkage internally.',
  'HR attendance and accounting dates preserve the selected local calendar date.',
  'Frontend, backend, npm package and .NET assembly versions are synchronized for every release.'
]
