namespace Garmetix.Api.Testing;

public static class TestAutomationCatalog
{
    public static IReadOnlyList<TestAutomationCheckDefinitionDto> BuildDefinitions() =>
    [
        new(
            "BACKEND_UNIT_TESTS",
            "Backend",
            "Run .NET unit tests",
            "dotnet test backend/Garmetix.Api.Tests/Garmetix.Api.Tests.csproj -c Release --no-restore",
            "All xUnit tests pass, including calculator, permission, purchase-return, vendor-settlement and test-automation contract tests.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "DASHBOARD_HOME_CONTRACT",
            "Backend",
            "Verify dashboard home routing contract",
            "dotnet test backend/Garmetix.Api.Tests/Garmetix.Api.Tests.csproj -c Release --filter FullyQualifiedName~DashboardHomeRoutingTests",
            "The /api/dashboard/home selector returns a JSON DashboardHomeDto for admin, HR, payroll and store roles.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "FRONTEND_BUILD",
            "Frontend",
            "Build Nuxt frontend",
            "cd frontend/garmetix-web && npm ci && npm run build",
            "Nuxt production build completes without remote icon/font fetch failures.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "FRONTEND_SMOKE",
            "Frontend",
            "Browserless frontend smoke test",
            "cd frontend/garmetix-web && npm run smoke:frontend",
            "The public web root returns the login page and proxied app-info endpoint reports the expected version.",
            "Medium",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "DOCKER_COMPOSE_BUILD",
            "Deployment",
            "Build Docker images",
            "docker compose --env-file .env.production -f docker-compose.prod.yml -f deploy/docker-compose.cloudflare.yml build",
            "API and web images build from the clean source package.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: false),
        new(
            "DOCKER_HEALTH",
            "Deployment",
            "Verify running production containers",
            "./deploy/diagnose-production.sh",
            "PostgreSQL is healthy, API answers /api/health, Nuxt answers /api/health through proxy, and web root returns HTTP 200.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: true),
        new(
            "FRONTEND_ROUTE_ACCESS_AUDIT",
            "Frontend",
            "Audit Nuxt route access coverage",
            "python3 scripts/validation/frontend-route-access-check.py",
            "Every concrete Nuxt page is covered by an explicit access-control rule or an approved public/dynamic exception.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "DOCKER_ACCEPTANCE_DRILL",
            "Deployment",
            "Run full Docker acceptance drill",
            "GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/docker-acceptance-drill.sh .env.production",
            "Production compose build/up, health, app-info, authenticated dashboard home, workspace/readiness and route-access checks all pass.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: true),
        new(
            "SECRET_HYGIENE_AUDIT",
            "Security",
            "Scan release package for local secrets",
            "python3 scripts/validation/secret-hygiene-check.py",
            "No local deployment env file, Cloudflare token or obvious private credential is present in the source package.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "FRONTEND_HYDRATION_GUARD",
            "Frontend",
            "Verify Nuxt auth hydration guard",
            "python3 scripts/validation/frontend-hydration-guard-check.py",
            "The app root uses ClientOnly plus mounted session restore so authenticated pages do not SSR-render stale auth shell content.",
            "Medium",
            RequiresDocker: false,
            RequiresLiveServer: false),

        new(
            "BACKUP_RESTORE_SAFETY",
            "Data Safety",
            "Verify backup/restore safety wiring and run disposable restore drill",
            "python3 scripts/validation/backup-restore-safety-check.py && ./scripts/linux/backup-restore-drill.sh .env.production",
            "Backup retention policy, restore preview contract, restore drill marker and disposable restore database procedure are present and host drill passes.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: false),
        new(
            "PERMISSION_ROLE_ACCEPTANCE",
            "Security",
            "Verify role-wise permission acceptance matrix",
            "python3 scripts/validation/permission-role-acceptance-check.py",
            "Permission acceptance endpoint exposes effective role matrix, required route expectations and frontend final acceptance page renders them.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "PRINT_PDF_ACCEPTANCE",
            "Print",
            "Verify final print/PDF acceptance catalog and live document endpoints",
            "python3 scripts/validation/print-pdf-acceptance-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/print-pdf-acceptance-drill.sh .env.production",
            "Print acceptance includes sales invoice/return, vouchers, petty cash, purchase, payroll, tailoring, non-GST and GST export samples; live ready endpoints return successfully.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "SMTP_DELIVERY_ACCEPTANCE",
            "Email",
            "Verify SMTP delivery configuration and optional live send",
            "python3 scripts/validation/smtp-delivery-acceptance-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/smtp-acceptance-drill.sh .env.production",
            "Email diagnostics exposes masked provider status, required env keys, admin-only test send, and the host drill can optionally send a real SMTP test email.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "LICENSE_SAAS_ACTIVATION",
            "Licensing",
            "Verify client license and SaaS activation workflow",
            "python3 scripts/validation/license-saas-activation-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/license-acceptance-drill.sh .env.production",
            "License Activation exposes signed client license generation, activation status, optional operational API enforcement and persistent activation storage.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "HR_EMPLOYEE_MASTER_ACCEPTANCE",
            "HR",
            "Verify upgraded employee master, photo and ID-card readiness",
            "python3 scripts/validation/hr-employee-master-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/hr-employee-master-acceptance-drill.sh .env.production",
            "Employee master includes auto employee code, photo, documents, store assignment, lifecycle and ID-card readiness contract.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "HR_BENEFITS_PAYROLL_ACCEPTANCE",
            "HR/Payroll",
            "Verify salary advance, leave, bonus, PF and gratuity adjustment workflow",
            "python3 scripts/validation/hr-benefits-payroll-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/hr-benefits-payroll-acceptance-drill.sh .env.production",
            "HR Benefits page and APIs expose payroll adjustments and generated payroll considers advance, bonus, leave encashment, PF and gratuity rows.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),

        new(
            "ATTENDANCE_CORE_ACCEPTANCE",
            "HR/Attendance",
            "Verify Attendance Core and kiosk API base",
            "python3 scripts/validation/stage9a-attendance-core-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/attendance-core-acceptance-drill.sh .env.production",
            "Attendance Core exposes models, schema repair, shifts/policies, device registration, kiosk bootstrap/lookup/punch/sync and payroll summary without real face/fingerprint matching.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "ATTENDANCE_KIOSK_PHOTO_PROOF",
            "HR/Attendance",
            "Verify kiosk photo proof and offline sync audit",
            "python3 scripts/validation/stage9b-kiosk-photo-proof-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/attendance-kiosk-photo-proof-drill.sh .env.production",
            "Stage 9B exposes kiosk readiness, photo-proof upload, web kiosk route, private proof storage and sync batch audit without real face recognition or fingerprint matching.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "ATTENDANCE_FACE_PHOTO_REVIEW",
            "HR/Attendance",
            "Verify face photo proof review and regularization foundation",
            "python3 scripts/validation/stage9c-face-photo-review-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/attendance-face-photo-review-drill.sh .env.production",
            "Stage 9C exposes manager review status for photo proofs, approve/reject/flag workflow, regularization linkage and retention visibility without real AI face recognition.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "ATTENDANCE_PAYROLL_REVIEW",
            "HR/Attendance",
            "Verify attendance payroll review foundation",
            "python3 scripts/validation/stage9d-attendance-payroll-review-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/attendance-payroll-review-drill.sh .env.production",
            "Stage 9D exposes payroll review rows generated from attendance monthly summaries with payable/deduction days, review status and no automatic payroll posting.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),

        new(
            "ATTENDANCE_SALARY_SLIP_GENERATION",
            "HR/Attendance",
            "Verify confirmed attendance salary slip generation",
            "python3 scripts/validation/stage9f-attendance-salary-generation-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/attendance-salary-generation-drill.sh .env.production",
            "Stage 9F generates final SalaryPaySlip records from ReadyForPayroll attendance salary drafts only after explicit confirmation, without salary payment or accounting voucher posting.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "ATTENDANCE_STAGE9_FINAL_ACCEPTANCE",
            "HR/Attendance",
            "Verify Stage 9 final attendance acceptance",
            "python3 scripts/validation/stage9-complete-attendance-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/attendance-stage9-final-drill.sh .env.production",
            "Stage 9 complete verifies salary payment candidates/generation, accounting posting guard, device bridge planning status and final acceptance endpoints.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "TODAYS_DASHBOARD_ACCEPTANCE",
            "Dashboard",
            "Verify Today's dashboard rollup",
            "python3 scripts/validation/stage9k-todays-dashboard-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/todays-dashboard-drill.sh .env.production",
            "The Dashboard section exposes Today's page and /api/dashboard/todays returns sales, purchase, receipt, payment, expense, cash voucher, trend and active employee attendance snapshots.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10A_FINAL_ACCEPTANCE",
            "Release",
            "Verify Stage 10A production final acceptance gate",
            "python3 scripts/validation/stage10a-production-final-acceptance-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/stage10a-production-final-acceptance-drill.sh .env.production",
            "Stage 10A verifies version identity, final acceptance API/page, route access, manifest coverage, production readiness, runtime smoke and key Stage 9/Today dashboard endpoints before moving ahead.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10B_IMPORT_EXPORT_CENTER",
            "Data",
            "Verify Stage 10B Excel Import Export Center",
            "python3 scripts/validation/stage10b-import-export-center-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/stage10b-import-export-center-drill.sh .env.production",
            "Stage 10B verifies safe production-final-acceptance fallback plus Excel-compatible CSV templates, exports, validation, attendance punch import/export and import/export center health endpoints.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10C_BARCODE_FINAL_ACCEPTANCE",
            "Print",
            "Verify barcode print final acceptance",
            "python3 scripts/validation/stage10-complete-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/stage10-complete-final-drill.sh .env.production",
            "Stage 10C exposes barcode print center, preview/generate APIs, product/stock/purchase inward label readiness and final acceptance page.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10D_GST_EINVOICE_ACCEPTANCE",
            "GST",
            "Verify GST/e-Invoice production readiness",
            "python3 scripts/validation/stage10-complete-check.py",
            "Stage 10D exposes GST/e-Invoice readiness, provider status, live-posting safety guard and final production acceptance checks.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10E_GOOGLE_DRIVE_BACKUP_ACCEPTANCE",
            "Data Safety",
            "Verify Google Drive backup sync readiness",
            "python3 scripts/validation/stage10-complete-check.py",
            "Stage 10E exposes masked Google Drive backup configuration, cloud sync readiness, local/cloud retention and backup safety notes.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10F_AUDIT_TRAIL_ACCEPTANCE",
            "Audit",
            "Verify audit trail and change history final acceptance",
            "python3 scripts/validation/stage10-complete-check.py",
            "Stage 10F exposes audit trail final acceptance, recent change-history rows, before/after JSON coverage and operator/request trace fields.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10_FINAL_ACCEPTANCE",
            "Release",
            "Verify complete Stage 10 final acceptance",
            "python3 scripts/validation/stage10-complete-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/stage10-complete-final-drill.sh .env.production",
            "Stage 10 final acceptance validates barcode, GST/e-Invoice, Google Drive backup and audit final acceptance endpoints/pages before moving to Stage 11/12.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10H_RUNTIME_DIAGNOSTICS",
            "Release",
            "Verify Stage 10H runtime diagnostics",
            "python3 scripts/validation/stage10h-runtime-bugfix-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/stage10h-runtime-diagnostics-drill.sh .env.production",
            "Stage 10H validates the runtime diagnostics page/API, database/table probes, page/API contracts and host-level smoke drill for post-deployment bug triage.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "STAGE10J_IMPORT_EXPORT_ENGINE",
            "Data",
            "Verify Stage 10J real import/export engine",
            "python3 scripts/validation/stage10j-import-export-engine-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/stage10j-import-export-engine-drill.sh .env.production",
            "Stage 10J validates product, customer, vendor, stock-opening, attendance and operational import/export modules plus safe validate-before-commit workflow.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "AUTHENTICATED_API_SMOKE",
            "API",
            "Authenticated production smoke test",
            "GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/smoke-test.sh .env.production",
            "Login returns a token and release/readiness/test-automation endpoints respond.",
            "Medium",
            RequiresDocker: false,
            RequiresLiveServer: true)
    ];
}
