namespace Garmetix.Api.Testing;

public static class TestAutomationCatalog
{
    public static IReadOnlyList<TestAutomationCheckDefinitionDto> BuildDefinitions() =>
    [
        new(
            "BACKEND_UNIT_TESTS",
            "Backend",
            "Run .NET unit tests",
            "dotnet test backend/Garmetix.Api.Tests/Garmetix.Api.Tests.csproj -c Release --no-restore",
            "All xUnit tests pass, including calculator, permission, purchase-return, vendor-settlement and test-automation contract tests.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "DASHBOARD_HOME_CONTRACT",
            "Backend",
            "Verify dashboard home routing contract",
            "dotnet test backend/Garmetix.Api.Tests/Garmetix.Api.Tests.csproj -c Release --filter FullyQualifiedName~DashboardHomeRoutingTests",
            "The /api/dashboard/home selector returns a JSON DashboardHomeDto for admin, HR, payroll and store roles.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "FRONTEND_BUILD",
            "Frontend",
            "Build Nuxt frontend",
            "cd frontend/garmetix-web && npm ci && npm run build",
            "Nuxt production build completes without remote icon/font fetch failures.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "FRONTEND_SMOKE",
            "Frontend",
            "Browserless frontend smoke test",
            "cd frontend/garmetix-web && npm run smoke:frontend",
            "The public web root returns the login page and proxied app-info endpoint reports the expected version.",
            "Medium",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "DOCKER_COMPOSE_BUILD",
            "Deployment",
            "Build Docker images",
            "docker compose --env-file .env.production -f docker-compose.prod.yml -f deploy/docker-compose.cloudflare.yml build",
            "API and web images build from the clean source package.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: false),
        new(
            "DOCKER_HEALTH",
            "Deployment",
            "Verify running production containers",
            "./deploy/diagnose-production.sh",
            "PostgreSQL is healthy, API answers /api/health, Nuxt answers /api/health through proxy, and web root returns HTTP 200.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: true),
        new(
            "FRONTEND_ROUTE_ACCESS_AUDIT",
            "Frontend",
            "Audit Nuxt route access coverage",
            "python3 scripts/validation/frontend-route-access-check.py",
            "Every concrete Nuxt page is covered by an explicit access-control rule or an approved public/dynamic exception.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "DOCKER_ACCEPTANCE_DRILL",
            "Deployment",
            "Run full Docker acceptance drill",
            "GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/docker-acceptance-drill.sh .env.production",
            "Production compose build/up, health, app-info, authenticated dashboard home, workspace/readiness and route-access checks all pass.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: true),
        new(
            "SECRET_HYGIENE_AUDIT",
            "Security",
            "Scan release package for local secrets",
            "python3 scripts/validation/secret-hygiene-check.py",
            "No local deployment env file, Cloudflare token or obvious private credential is present in the source package.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "FRONTEND_HYDRATION_GUARD",
            "Frontend",
            "Verify Nuxt auth hydration guard",
            "python3 scripts/validation/frontend-hydration-guard-check.py",
            "The app root uses ClientOnly plus mounted session restore so authenticated pages do not SSR-render stale auth shell content.",
            "Medium",
            RequiresDocker: false,
            RequiresLiveServer: false),

        new(
            "BACKUP_RESTORE_SAFETY",
            "Data Safety",
            "Verify backup/restore safety wiring and run disposable restore drill",
            "python3 scripts/validation/backup-restore-safety-check.py && ./scripts/linux/backup-restore-drill.sh .env.production",
            "Backup retention policy, restore preview contract, restore drill marker and disposable restore database procedure are present and host drill passes.",
            "High",
            RequiresDocker: true,
            RequiresLiveServer: false),
        new(
            "PERMISSION_ROLE_ACCEPTANCE",
            "Security",
            "Verify role-wise permission acceptance matrix",
            "python3 scripts/validation/permission-role-acceptance-check.py",
            "Permission acceptance endpoint exposes effective role matrix, required route expectations and frontend final acceptance page renders them.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: false),
        new(
            "PRINT_PDF_ACCEPTANCE",
            "Print",
            "Verify final print/PDF acceptance catalog and live document endpoints",
            "python3 scripts/validation/print-pdf-acceptance-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/print-pdf-acceptance-drill.sh .env.production",
            "Print acceptance includes sales invoice/return, vouchers, petty cash, purchase, payroll, tailoring, non-GST and GST export samples; live ready endpoints return successfully.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "SMTP_DELIVERY_ACCEPTANCE",
            "Email",
            "Verify SMTP delivery configuration and optional live send",
            "python3 scripts/validation/smtp-delivery-acceptance-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/smtp-acceptance-drill.sh .env.production",
            "Email diagnostics exposes masked provider status, required env keys, admin-only test send, and the host drill can optionally send a real SMTP test email.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "LICENSE_SAAS_ACTIVATION",
            "Licensing",
            "Verify client license and SaaS activation workflow",
            "python3 scripts/validation/license-saas-activation-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/license-acceptance-drill.sh .env.production",
            "License Activation exposes signed client license generation, activation status, optional operational API enforcement and persistent activation storage.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "HR_EMPLOYEE_MASTER_ACCEPTANCE",
            "HR",
            "Verify upgraded employee master, photo and ID-card readiness",
            "python3 scripts/validation/hr-employee-master-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/hr-employee-master-acceptance-drill.sh .env.production",
            "Employee master includes auto employee code, photo, documents, store assignment, lifecycle and ID-card readiness contract.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "HR_BENEFITS_PAYROLL_ACCEPTANCE",
            "HR/Payroll",
            "Verify salary advance, leave, bonus, PF and gratuity adjustment workflow",
            "python3 scripts/validation/hr-benefits-payroll-check.py && GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/hr-benefits-payroll-acceptance-drill.sh .env.production",
            "HR Benefits page and APIs expose payroll adjustments and generated payroll considers advance, bonus, leave encashment, PF and gratuity rows.",
            "High",
            RequiresDocker: false,
            RequiresLiveServer: true),
        new(
            "AUTHENTICATED_API_SMOKE",
            "API",
            "Authenticated production smoke test",
            "GARMETIX_SMOKE_USER=admin GARMETIX_SMOKE_PASSWORD=*** ./scripts/linux/smoke-test.sh .env.production",
            "Login returns a token and release/readiness/test-automation endpoints respond.",
            "Medium",
            RequiresDocker: false,
            RequiresLiveServer: true)
    ];
}
