<script setup lang="ts">
import { h, resolveComponent } from 'vue'
import type { TableColumn } from '@nuxt/ui'
const api=useGarmetixApi(); const auth=useAuth(); const workspace=useWorkspace(); const feedback=useUiFeedback(); const isAuthenticated=auth.isAuthenticated; const canEdit=auth.canEdit; const canDelete=auth.canDelete
const UButton=resolveComponent('UButton'); const UBadge=resolveComponent('UBadge'); const rows=ref<any[]>([]); const search=ref(''); const loading=ref(false); const loadError=ref(''); const formOpen=ref(false); const saving=ref(false); const form=reactive<any>({id:'',companyId:'',name:'',productGroup:2,isActive:true})
const productGroups=[{value:0,label:'Shirting'},{value:1,label:'Suiting'},{value:2,label:'Readymade'},{value:3,label:'Sherwani'},{value:4,label:'Suits'},{value:5,label:'Blazers'},{value:6,label:'Kurta'},{value:7,label:'Kurta Pajama'},{value:8,label:'Pajama'},{value:9,label:'Pagadi'},{value:10,label:'Dupatta'},{value:11,label:'Pagadi Dupatta Set'},{value:12,label:'Brochs'},{value:13,label:'Kalgi'},{value:14,label:'Jodhpuri'},{value:15,label:'Winter Wear'},{value:16,label:'Inner Wear'},{value:17,label:'Shoes'},{value:18,label:'Nagra'},{value:19,label:'Accessories'},{value:20,label:'Others'}]
const filteredRows=computed(()=>rows.value.filter((r:any)=>!search.value || [r.name,r.productGroupName].some(v=>String(v||'').toLowerCase().includes(search.value.toLowerCase()))))
const columns:TableColumn<any>[]=[{accessorKey:'name',header:'Category'},{accessorKey:'productGroupName',header:'Product Group'},{accessorKey:'isActive',header:'Status',cell:({row})=>h(UBadge,{color:row.original.isActive?'success':'neutral',variant:'subtle'},()=>row.original.isActive?'Active':'Inactive')},{id:'actions',header:'',cell:({row})=>h('div',{class:'flex justify-end gap-1'},[h(UButton,{icon:'i-lucide-pencil',label:'Edit',size:'sm',variant:'ghost',disabled:!canEdit.value,onClick:()=>startEdit(row.original)}),h(UButton,{icon:'i-lucide-trash-2',label:'Delete',size:'sm',variant:'ghost',color:'error',disabled:!canDelete.value,onClick:()=>removeRow(row.original)})])}]
async function refresh(){loading.value=true; loadError.value=''; try{rows.value=await api.list<any>('masters/product-categories')}catch(e:any){loadError.value=e.message||'Category load failed'; feedback.failed('Category load failed',e)}finally{loading.value=false}}
function startCreate(){Object.assign(form,{id:'',companyId:workspace.companyId.value||'',name:'',productGroup:2,isActive:true}); formOpen.value=true} function startEdit(row:any){Object.assign(form,{...row,productGroup:Number(row.productGroup ?? 2)}); formOpen.value=true}
async function save(){saving.value=true; try{if(!form.companyId) throw new Error('Select company/workspace first.'); if(form.id) await api.update<any>('masters/product-categories',form.id,form); else await api.create<any>('masters/product-categories',form); feedback.saved('Category saved'); formOpen.value=false; await refresh()}catch(e:any){feedback.failed('Category save failed',e)}finally{saving.value=false}}
async function removeRow(row:any){if(!confirm(`Delete or inactivate category ${row.name}?`)) return; try{await api.remove('masters/product-categories',row.id); feedback.notify('Category removed'); await refresh()}catch(e:any){feedback.failed('Category delete failed',e)}}
onMounted(()=>{auth.restore(); refresh()})
</script><template><AuthScreen v-if="!isAuthenticated" @authenticated="refresh"/><AppShell v-else title="Product Categories" @refresh="refresh" @workspace-change="refresh"><section class="planner-dashboard"><UiModulePageHeader title="Product Category Master" description="Manage category and product group mapping used by inventory and purchase import." icon="i-lucide-folder-tree" primary-label="New Category" primary-icon="i-lucide-plus" @primary="startCreate"/><UiRegisterPanel title="Categories" :loading="loading" :error="loadError" :empty="filteredRows.length===0" empty-title="No categories" empty-description="Add a category or change search." empty-icon="i-lucide-folder-tree" @retry="refresh"><template #actions><UiCrudToolbar v-model:search="search" search-placeholder="Search category/group" :loading="loading" create-label="New Category" @refresh="refresh" @create="startCreate"/></template><div class="planner-table-wrap"><UTable :data="filteredRows" :columns="columns"/></div></UiRegisterPanel><UiFormSlideover v-model:open="formOpen" :title="form.id?'Edit Category':'New Category'" submit-label="Save Category" :loading="saving" @submit="save"><UFormField label="Category name" required><UInput v-model="form.name" required/></UFormField><UFormField label="Product group"><USelect v-model="form.productGroup" :items="productGroups"/></UFormField><UCheckbox v-model="form.isActive" label="Active category"/></UiFormSlideover></section></AppShell></template>
