using System.Diagnostics;
using System.Reflection;

namespace Garmetix.Api.AppInfo;

public static class AppInfoEndpoints
{
    public const string ProductName = "Garmetix";
    public const string Version = "4.12.69";
    public const string Stage = "Stage 11D-154 Stock Operation Product Autocomplete";
    public const string ReleaseName = "Stage 11D-154: Stock Operation Product Autocomplete";
    public const string BuildDate = "2026-07-03";
    public const string BuildCode = "GARMETIX-11D154-20260703-4269";

    public static RouteGroupBuilder MapAppInfoEndpoints(this WebApplication app)
    {
        var group = app.MapGroup("/api/app-info")
            .WithTags("App Info")
            .AllowAnonymous();

        group.MapGet("", Info);
        group.MapGet("/version", VersionOnly);
        group.MapGet("/faq", Faq);
        group.MapGet("/contacts", Contacts);
        group.MapGet("/system", SystemInfo);

        return group;
    }

    private static IResult Info(IHostEnvironment environment)
        => Results.Ok(Create(environment.EnvironmentName));

    private static IResult VersionOnly(IHostEnvironment environment)
        => Results.Ok(new
        {
            productName = ProductName,
            version = Version,
            stage = Stage,
            releaseName = ReleaseName,
            buildDate = BuildDate,
            buildCode = BuildCode,
            environment = environment.EnvironmentName,
            assemblyVersion = Assembly.GetExecutingAssembly().GetName().Version?.ToString()
        });


    private static IResult SystemInfo(IHostEnvironment environment)
    {
        var startedAt = Process.GetCurrentProcess().StartTime.ToUniversalTime();
        var now = DateTime.UtcNow;
        return Results.Ok(new AppSystemInfoDto(
            ProductName,
            Version,
            Stage,
            ReleaseName,
            BuildDate,
            BuildCode,
            environment.EnvironmentName,
            now.ToString("O"),
            startedAt.ToString("O"),
            Convert.ToInt64((now - startedAt).TotalSeconds),
            Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? string.Empty));
    }

    private static IResult Faq() => Results.Ok(FaqItems);

    private static IResult Contacts() => Results.Ok(ContactItems);

    private static AppVersionDto Create(string environment)
        => new(
            ProductName,
            Version,
            Stage,
            ReleaseName,
            BuildDate,
            BuildCode,
            environment,
            Highlights,
            ContactItems,
            FaqItems);

    private static readonly string[] Highlights =
    [
        "Stage 11D-154 replaces Stock Operations product dropdowns with searchable autocomplete pickers across Adjustment, Transfer, Physical Count and Write-off tabs, including barcode/store/stock/MRP selection hints.",
        "Stage 11D-153 fixes the Financial Year Closeout metric DTO constructor mismatch, removes invalid StoreGroupId access from sale invoice closeout scope, and computes production go-live purchase paid evidence from PurchasePayment rows instead of a missing PurchaseInvoice.Paid field.",
        "Stage 11D-150 adds Production Host Build QA plus Purchase Return Advanced Settlement acceptance with formal supplier return, exact ITC reversal, debit-note settlement, refund bank proof and accounting audit evidence.",
        "Stage 11D-149 adds Final Owner Sign-off with Ready / Not Ready status, printable owner declaration, CSV sign-off evidence and signature-proof checklist.",
        "Stage 11D-148 adds Production Go-Live Master Acceptance with master setup, sales, purchase, stock, accounting, bank, return, payroll, FY-lock and backup/restore gate checks.",
        "Stage 11D-147 adds Owner Closeout Command Center with profit, stock valuation, customer dues, vendor payable, note control, bank settlement and journal-balance evidence in one CSV-ready dashboard.",
        "Stage 11D-146 adds Stock Valuation Closure with negative-stock, zero-cost, movement-proof and stock-type valuation evidence before month/FY close.",
        "Stage 11D-145 adds invoice-wise and item-wise Profit/Loss reporting using sale item revenue and linked stock-out cost evidence.",
        "Stage 11D-144 adds Bank Reconciliation / Payment Settlement Closure with Complete / Not Complete status, CSV evidence export, non-cash settlement rows, payment-mode summaries, bank-account evidence, bank transaction journal checks and statement-line reconciliation warnings.",
        "Stage 11D-143 adds a Financial Year Closeout Dashboard with Complete / Not Complete status, consolidated section matrix, GST/accounting checks, customer/vendor balances, payroll readiness, stock risk, FY lock evidence and CSV closeout export.",
        "Stage 11D-141 adds Vendor Payable / Purchase Settlement Reconciliation with Complete / Not Complete status, CSV evidence export, vendor master bill/paid checks, invoice status/payment-row checks, debit-note settlement checks, voucher/journal evidence and non-cash bank mapping validation.",
        "Stage 11D-140 adds Customer Dues / Credit Balance Reconciliation with Complete / Not Complete status, CSV evidence export, customer-wise due/advance/credit-note checks, non-cash advance bank mapping checks, closeout checklist and next-module handoff guidance.",
        "Stage 11D-139 adds a public Goods Return & Exchange Policy page, links it from digital invoice pages, and prints the policy URL/summary on invoice PDFs with no refund and credit-note validity guidance.",
        "Stage 11D-138 wraps acceptance, GST, backup and maintenance pages inside the main AppShell, keeps navigation/sidebar/header visible, carries the LX-310 CRLF bridge hotfix, and hardens Attendance Kiosk Monitor APIs against older live database schemas.",
        "Stage 11D-129 adds final Print/PDF closure status, CSV evidence export, core sale/purchase sample blocking, live-printer operator rules, closeout checklist and next-module handoff guidance.",
        "Stage 11D-128 adds Day Book CSV evidence export, print/save-PDF view, export closure card, 5,000-row export scope and stronger source-opening return hints with source ID/type/date anchors.",
        "Stage 11D-127 adds Accounting/GST post-import live validation with Complete / Not Complete status, CSV evidence, GST/payment summaries, journal checks, stock movement checks, purchase-import proof acceptance checks, closeout checklist and next-module handoff guidance.",
        "Stage 11D-126 adds Attendance/Payroll real-month validation with Complete / Not Complete status, blocking/warning issue list, employee-wise evidence table, CSV export, final closeout checklist, known limitations and next outside-module handoff guidance.",
        "Stage 11D-124 closes Purchase Import with a Complete / Not Complete status, final closeout checklist, visible known limitations and next outside-module handoff guidance.",
        "Stage 11D-123 adds purchase import correction/revision guidance, parser QA summaries, and backup/restore proof checklists for safer real-invoice acceptance.",
        "Stage 11D-121 makes sale invoice barcode visibility mandatory in receipt view and print/PDF output, and adds wrapped/collapsible invoice remarks in the sale invoice list.",
        "Stage 11D-118 adds public Privacy Policy and Terms of Usage pages for Meta/WhatsApp verification, fixes the /privcy spelling with a redirect to /privacy, and exposes both pages without login.",
        "Stage 11D-117 keeps the Meta Cloud API fixes and aligns invoice WhatsApp sends to the 4-variable Aadwika approved template: customer, invoice number, amount and public bill URL.",
        "Stage 11D-114 polishes Purchase Inward final QA with inward-date based register filtering, clearer inward/entry date columns, wider purchase receipt view, purchase deep-link aliases and Day Book-aware return from new/revised inward.",
        "Stage 11D-113 completes vendor payment final QA polish with view, edit, delete, direct payment deep-link opening and Day Book vendor-payment source links routed to the Vendor Payments page.",
        "Stage 11D-112 adds Back to Day Book return navigation on sale, purchase, voucher, cash voucher, vendor payment and accounting source pages while preserving the last Day Book date/type/search/page state.",
        "Stage 11D-108 restores the missing Day Book plus/New button with quick-create actions for sale, purchase, vendor payment, voucher and cash voucher, and fixes route/menu validation hygiene.",
        "Stage 11D-107 adds source page deep links from Day Book so sale invoice, purchase inward, vendor payment, voucher and cash voucher rows open their exact detail/print drawer on the original page.",
        "Stage 11D-104 adds admin purchase/vendor payment reconciliation endpoints to report and repair vendor paid totals, purchase invoice payment status/mode, and stale voucher/accounting artifacts after vendor payment edit/delete.",
        "Stage 11D-103 hardens vendor payment edit/delete by recalculating vendor paid totals and purchase invoice status from active payment rows, clearing stale bank artifacts when payment mode changes to cash, and allowing payment reference/remark correction.",
        "Stage 11D-100 makes purchase inward date user-controlled on new/edit purchase inward and posts stock ledger/purchase payment dates from the selected inward date.",
        "Stage 11D-99 fixes historical Vyapar sale import stock posting by checking ledger availability on the sale date and creating controlled bridge stock before stock-out when enabled.",
        "Stage 11D-96 enforces exact bank/POS/UPI column-to-bank-account mapping for Vyapar sale import so each non-cash receipt posts to the correct Garmetix bank ledger, with default bank kept only as fallback for old files.",
        "Stage 11D-94 fixes deployed database drift by ensuring SalesInvoices.Remarks exists at startup and adds runtime repair scripts for sale list, replacement approval and Vyapar imported invoice endpoints.",
        "Stage 11D-93 adds Vyapar import batch history, admin-only batch undo/reversal, bulk barcode mapping upload, mismatch export workflow, and final approval before database posting.",
        "Stage 11D-91 adds Vyapar Sale Import runtime validation scripts, database safety checks, deployment smoke checks, import verification guidance and explicit next-stage tracking for batch undo and barcode mapping upload.",
        "Stage 11D-88 adds Vyapar Sale Import for Sale Report Excel files with backend preview, barcode/stock matching, missing-product review, optional product/stock bridge creation and confirm-to-database posting.",
        "Stage 11D-87 adds Product Master size-wise filtering, detected size display, and server-side size filtering for imported/split stock items.",
        "Stage 11D-83 adds Purchase Import Acceptance: final QA summary, posting report endpoint/page, readiness checklist, status-wise import health, protected proof storage visibility and recent batch diagnostics before moving outside purchase import.",
        "Stage 11D-82 adds Cash Details day reconciliation, CSV export, copy-as-verification, denomination breakdown and variance checks against Day Opening/Closing and petty cash sheet cash-in-hand.",
        "Stage 11D-81 links posted supplier invoice imports and purchase inwards directly to price-tag printing, supports route-based auto-loading into 50×30/50×25 tag pages, and adds reprint tag actions from purchase invoice list/receipt.",
        "Stage 11D-80 adds supplier invoice import storage summary: protected posted proof bytes, unposted OCR/proof storage, status-wise draft counts, and refreshable storage visibility on the import page.",
        "Stage 11D-77 adds purchase import posting QA: stricter gross/discount/taxable/grand-total reconciliation, size split templates, bulk similar-product scanning, and failed/rejected scanned-history cleanup while protecting posted proofs.",
        "Stage 11D-76 restores the missing column product-name helper used by the Tally/S.K APPARELS discount parser so API publish succeeds while keeping line-discount reconciliation intact.",
        "Stage 11D-70 adds supplier invoice review tools: draft health summary, bulk default copying, MRP fill, ignored-line restore, and duplicate barcode blocking before posting.",
        "Stage 11D-67 improves supplier invoice recognition with item-table detection, header/footer filtering, amount plausibility checks, and vendor-wise correction learning.",
        "Stage 11D-63 adds optional local OCR helpers for supplier invoice PDFs/images, stronger parser heuristics for HSN/qty/rate/GST/line totals, extracted text download and draft reparse usability.",
        "Stage 11D-62 improves supplier invoice import with GST inclusive/exclusive review, product matching, duplicate override audit and proof backup retention.",
        "Stage 11D-60 restores missing campaign WhatsApp helper methods so API publish succeeds after the Digital Bill permission and UI polish slice.",
        "Stage 11D-58 adds approved WhatsApp marketing-template campaign sending, production readiness checks, and Digital Bill CRM final acceptance page.",
        "Stage 11D-53 fixes Nuxt UI SelectItem runtime crashes by replacing empty-string store filter options with safe sentinel values in Digital Bill Ad Banners and Analytics pages.",
        "Stage 11D-52 adds a Digital Bill Activity drawer with customer opens, PDF downloads, review/social clicks, banner clicks, feedback submissions and WhatsApp delivery/read history, and fixes the v4.11.66 Digital Bill generate endpoint signature typo.",
        "Stage 11D-50 fixes Digital Bill manual generation so admin users can generate customer invoice links from either the sale invoice GUID or the visible invoice number such as S-20260625-0001.",
        "Stage 11D-48 adds WhatsApp provider settings, ManualOnly/MetaCloudApi dispatch, auto-send after sale finalization, resend/retry logs, and public DigitalBills__PublicBaseUrl support.",
        "Stage 11D-47 adds Digital Bill CRM MVP with secure public invoice links, PDF download, review/social settings, private feedback, public noindex invoice page, admin Digital Bills register, permissions, schema repair and roadmap docs.",
        "Stage 11D-46 adds a runtime validation runner for Docker build/up, API health, app-info version, web reachability, DB connectivity, sale payment mismatch checks, mixed-payment allocation review, invoice replacement readiness and Royalwood import validation hooks.",
        "Stage 11D-46 keeps v4.11.60 functional fixes intact and packages final deployment checks so post-deploy issues can be caught before store use.",
        "Stage 11D-43 fixes the API publish failure in InvoiceReplacementEndpoints by removing the invalid PurchaseInvoice.PaidAmount reference and keeping purchase replacement approval audit snapshots compatible with the current domain model.",
        "Invoice replacement pending sales now uses a safe fallback party name to remove the nullable PartyName warning during publish.",
        "Stage 11D-42 stores final PDF/print acceptance evidence in AuditLogEntries and expands Print Final Acceptance into sale/purchase A4/A5, large invoice, amount box, footer, signature and page-summary checks.",
        "Print Final Acceptance now has backend evidence history so final handover proof survives browser/device changes.",
        "Stage 11D-41 adds invoice replacement approval so revised sale/purchase invoices are linked to originals and old invoices are cancelled/reversed only after owner/admin approval.",
        "Invoice Replacement Approvals now shows pending revised invoices and an audit ledger for requested, approved, completed and failed replacement events.",
        "Stage 11D-40 hardens payroll finalization with one backend transaction for review approval, salary draft preparation, payslip generation, optional salary payment posting, payroll adjustment recovery and month locking.",
        "Stage 11D-38 adds multi-select bulk delete to Monthly Attendance with selected employee/date deletion, linked punch cleanup and locked-month protection.",
        "Stage 11D-37 makes backup files portable and visible after redeploy by scanning backup folders recursively and naming backups with company, app version, IST date/time and sequence number.",
        "Stage 11D-29 applies GSTIN state-code tax splitting for purchase and sale invoices and changes sales invoice numbering to StoreCode/YYYYMM/INV/series.",
        "Stage 11D-16 adds multi-page Tally-style A4/A5 purchase and sales invoice PDFs with page summary and final grand totals.",
        "Stage 11D-11 adds housekeeping double-shift handling, admin/owner timing correction for check-in/break/check-out, shift CRUD protection, restricted shift-rule management, and duplicate punch no-error handling.",
        "Stage 11D-3 changes the HR Attendance tab to month-scoped server-side pagination so full attendance history imports do not slow the HR page.",
        "Stage 11D-1 guards startup migrations when an old Docker/Postgres volume already has Garmetix tables but the fresh Initial migration history marker is missing.",
        "Stage 11D resets EF migrations to one current Initial baseline and adds app super-admin, Indian accounting defaults and automatic Manager salesman defaults.",
        "Stage 11C-2 adds face/liveness simulator and local/private external bridge proof checks with Message Logs and raw face payload blocking.",
        "Stage 11C adds a privacy-safe face liveness readiness contract with blocked raw payload fields, provider checklist and operator page.",
        "Stage 11B-10 adds Windows and Linux Mantra contract rehearsal drills for safe enroll and raw-response blocking.",
        "Stage 11B-9 adds a local Mantra mock service harness for safe adapter rehearsal before the official SDK/service is installed.",
        "Stage 11B-8 adds a configurable Mantra local-service adapter with localhost/private-LAN URL guards, response normalization and raw biometric field blocking.",
        "Stage 11B-7 marks Mantra as the selected fingerprint device target and wires bridge enroll results into biometric enrollment reference capture.",
        "Stage 11B-6 hardens biometric enrollment with explicit consent validation, safe template references, readable employee rows, revocation workflow and Message Logs.",
        "Stage 11B-5 adds configurable kiosk fingerprint punch enforcement with local bridge proof validation, operator UI and Message Logs for blocked punches.",
        "Stage 11B-4 adds a runnable local fingerprint bridge service template with simulator adapter, local/private caller guard and no raw biometric payload output.",
        "Stage 11B-3 adds a guarded external fingerprint bridge connector for localhost/private vendor bridges with sanitized Message Logs and raw biometric field blocking.",
        "Stage 11B-2 adds a fingerprint bridge simulator handshake for health, capture, identify and enroll with sanitized Message Logs and no biometric payload storage.",
        "Stage 11B adds a vendor-neutral fingerprint bridge contract, readiness page, adapter checklist and privacy guard before any real SDK integration.",
        "Stage 11A physical tablet rehearsal adds an operator checklist, evidence capture contract and pass/fail criteria before fingerprint hardware work.",
        "Stage 11A build hardening removes the MAUI MainPage startup warning and adds Android build, APK/AAB, advisory and hardware rehearsal visibility.",
        "Stage 11A adds the native MAUI Android Attendance Kiosk shell, SQLite pending punch queue and web status page for the mobile kiosk contract.",
        "Stage 10M adds a Production Rehearsal page and API for live-data run sheets, blocking checks, issue buckets and go/no-go evidence before Stage 11.",
        "Stage 10L adds a Production Support page and API for failed save, failed print, backup warning, email/share failure and Cloudflare or hosted API mismatch drills.",
        "Stage 10K adds a production operator acceptance page and API for daily store opening, billing, cash closing, purchase, accounting, HR/payroll, backup and support rehearsal.",
        "Import/Export CSV download and upload now use hosted-safe API URLs with sanitized CSV filenames.",
        "Salary payment slips now have a direct PDF download action with safe filenames for SPAY voucher numbers.",
        "Voucher PDF downloads now use the shared document helper so hosted deployments avoid localhost API URLs and keep cleaner error messages.",
        "Petty Cash PDF now paginates all A5 transaction-detail rows instead of truncating busy cash sheets.",
        "Sale invoice acceptance validation now protects the dedicated full-page invoice flow, draft recovery, compact controls, Manager fallback, payment safety and automatic first print.",
        "Dashboard shell now uses one main vertical scroller with stable panel scrollbars while preserving horizontal table scroll.",
        "Notifications now mark the badge read using the newest valid visible alert timestamp and route each alert to its related module.",
        "System Info now uses the compact module header pattern instead of the oversized dashboard hero.",
        "System Health now shows Oracle secondary sync readiness, direction, wallet, tenant/source and last success.",
        "Company page helper text now wraps cleanly while header actions remain grouped as usable controls.",
        "Sale invoices now recover the internal Manager salesman automatically when a store has no active salesman master.",
        "Stage 10J adds a real import/export engine for products, customers, vendors, stock opening, billing, purchase, HR, payroll, attendance, vouchers, petty cash and access.",
        "Stock Opening import adjusts store-wise stock ledgers to the uploaded opening quantity and records an auditable stock movement.",
        "Customer and vendor master import/export are now first-class modules with templates, validation, create/update behavior and error report download.",
        "Stage 10I makes Day Closing use today's Day Open opening balance for petty cash book cash instead of silently overriding it with previous closing.",
        "Stage 10I warns when today's opening balance differs from the previous petty cash sheet closing balance and requires confirmation before closing.",
        "Store Operations now shows a Day Closing petty cash preview popup so calculated petty cash values can be reviewed and corrected before save.",
        "Stage 10H adds /runtime-diagnostics with safe database table probes for post-deployment bug triage.",
        "Runtime diagnostics lists important page/API contracts so frontend 500 errors can be traced to the exact backend endpoint.",
        "A host-level Stage 10H drill verifies the runtime diagnostics endpoints after Docker restart.",
        "Stage 10G verifies every concrete Nuxt page is discoverable from both modern and legacy sidebars.",
        "Sidebar now includes direct create links for New Sale Invoice, New Customer, New Debit Note and New Credit Note.",
        "Legacy sidebar now mirrors the modern navigation so DASHBOARD_SHELL=legacy deployments do not hide Stage 9/10 pages.",
        "Stage 10A adds a consolidated Production Final Acceptance page and API for the complete release gate.",
        "Test Automation runtime smoke now accepts current GARMETIX build-code families instead of stale Stage 8-only prefixes.",
        "Stage 10A host drill checks health, app-info, production readiness, runtime smoke, Today\'s dashboard, attendance final acceptance and the final acceptance gate.",
        "Release validation now includes TypeScript app-version string safety, route-access coverage, secret hygiene and Stage 10A acceptance contracts.",
        "Dashboard section now includes a Today's page with sales, purchase, receipt, payment, expense, cash voucher and active employee attendance snapshots.",
        "Today's dashboard includes last-14-day sales, purchase and gross-margin line graph data for the selected workspace.",
        "Stage 9 Complete finishes Attendance Core through final acceptance: kiosk base, photo proof, review, payroll review, salary draft, salary slip generation, confirmed salary payment posting, and device bridge planning.",
        "Stage 9G can generate SalaryPayment records from attendance-generated payslips only after explicit confirmation.",
        "Stage 9H uses the existing audited SalaryPayment accounting workflow when confirmed payments are generated.",
        "Stage 9I keeps fingerprint device bridge integration-ready without enabling raw fingerprint storage or vendor matching.",
        "Stage 9J adds final acceptance visibility for completed attendance features and remaining future kiosk/biometric work.",
        "Stage 9F can generate final SalaryPaySlip records from ReadyForPayroll attendance salary drafts after explicit user confirmation.",
        "Salary payment creation and accounting voucher posting remain separate workflows and are not triggered by attendance salary slip generation.",
        "Stage 9E adds salary slip draft preview rows from reviewed attendance payroll review data without posting payroll, vouchers, or salary slips.",
        "Attendance salary draft preview can be rebuilt and marked ReadyForPayroll or OnHold, but remains PreviewOnly until a later approved package.",
        "Stage 9D adds attendance payroll review rows with payable days, deduction days, overtime minutes, lock visibility, and review status without posting payroll.",
        "Attendance payroll review can be rebuilt from monthly attendance summaries and marked Reviewed, ApprovedForPayroll, or OnHold.",
        "Stage 9C adds manager face photo proof review, approve/reject/flag workflow, regularization linkage, retention visibility, and audit-ready photo status.",
        "Kiosk API base includes device registration, heartbeat, employee lookup, punch and sync-pending endpoints for future Android/MAUI kiosk apps.",
        "Face attendance is limited to photo-proof path placeholders; real face recognition and liveness checks remain future packages.",
        "Fingerprint support is limited to enrollment/device bridge placeholders; no raw fingerprint image is stored.",
        "Payroll attendance summary is available for review only; automatic salary deduction/posting remains a later package.",
        "Employee save now uses a PostgreSQL-translatable nullable MaxAsync sequence query and avoids EF Core DefaultIfEmpty translation failures during PUT /api/employees.",
        "Frontend dependency cleanup removes deprecated lucide-vue-next from package metadata because Nuxt UI already uses Iconify lucide icons.",
        "HR Employee Master now supports auto employee code, photo preview, document/bank fields, lifecycle status and printable ID-card readiness.",
        "HR Benefits adds salary advance, advance recovery, leave, bonus, leave encashment, PF and gratuity adjustment workflow for payroll.",
        "Payroll generation and payment preview now consider HR Benefits adjustments such as advances, bonus, PF and gratuity rows.",
        "License Activation now provides signed client license generation, activation, status review and optional SaaS operational API enforcement.",
        "Docker/env templates include LICENSE_* settings and a persistent license activation volume for production deployments.",
        "Test Automation includes LICENSE_SAAS_ACTIVATION for license status and host acceptance verification.",
        "Email Delivery now has a dedicated admin page for masked SMTP status, provider guidance and live test email acceptance.",
        "SMTP diagnostics now identify common providers, return required environment keys and include a safe timeout contract without exposing secrets.",
        "A Linux SMTP acceptance drill validates the diagnostics contract and can optionally send a real host-level test email.",
        "Docker/env templates now include EMAIL_TIMEOUT_SECONDS for safer SMTP delivery troubleshooting.",
        "Print Final Acceptance now covers sales invoice/return, vouchers, petty cash, purchase inward/return, debit/credit notes, non-GST goods, tailoring, payroll and GST export samples.",
        "Store Manager and biller users now land first on Store Operations after login so day opening happens before billing.",
        "Store Day Open / Close UI label is renamed to Store Operations across route access, menu, page title and backend tag.",
        "The release manifest now includes PRINT_PDF_ACCEPTANCE and a live print/PDF acceptance drill script for production hosts.",
        "Restore preview now checks pg_restore readability, core Garmetix table coverage, backup manifest stage, and version mismatch warnings before restore.",
        "Backup retention supports both retention days and a keep-minimum policy so scheduled cleanup does not remove all safe restore points.",
        "The Linux backup/restore drill creates a dump, restores it into a disposable PostgreSQL database, verifies required tables, and writes a restore-drill marker without touching production data.",
        "Production Readiness now reports both latest backup health and disposable restore-drill status.",
        "Permission Final Acceptance now exposes the effective role matrix, required route expectations, test-user coverage and blocked-route acceptance checklist.",
        "Local deployment env files are excluded from release archives and repository tracking.",
        "Secret hygiene validation scans for Cloudflare API tokens, local env files and obvious private credentials before packaging.",
        "Nuxt uses a client hydration gate so authenticated dashboard pages render after browser session restore and avoid shared SSR/auth shell mismatches.",
        "Docker acceptance drill now verifies build, container health, authenticated dashboard routing, workspace/readiness endpoints, and route-access coverage.",
        "The release manifest now includes DOCKER_ACCEPTANCE_DRILL and FRONTEND_ROUTE_ACCESS_AUDIT so production smoke checks cover host-level acceptance.",
        "Linux and Windows acceptance scripts can run the full deployment drill from a single command before go-live.",
        "/api/dashboard/home now returns an explicit DashboardHomeDto JSON body for role-based dashboard routing.",
        "Release smoke checks now include dashboard-home contract validation.",
        "Linux and Windows smoke scripts validate dashboard/home after authenticated login.",
        "Frontend route access now covers Cash Details, Store Day, Tailoring, backup and final acceptance pages.",
        "Cash Details API now requires Accounting matrix permission and validates cash denomination payloads.",
        "Linked Day Opening and Day Closing cash details cannot change store, date or source during edit.",
        "Store Day API authorization now matches store operational roles through the Billing permission matrix.",
        "Automated backend, frontend and production smoke-test scripts now ship with the release package.",
        "The API exposes a test-automation manifest and runtime smoke endpoint for deployment validation.",
        "Frontend smoke checks verify the public login page and proxied app-info endpoint without a browser driver.",
        "Linux, WSL and Windows test runners can execute backend unit tests, Nuxt build checks and optional Docker health checks.",
        "Tailoring and alteration orders now follow order-delivery-invoice-payment SOP with delivery schedule, pending, delivered, invoiced, paid and completed status tracking.",
        "Readymade garment alteration can be assigned to tailoring vendors with customer-chargeable, in-house expense, or complimentary cost responsibility.",
        "Tailoring service items are reusable in orders and service invoice conversion, with default customer rate, vendor rate, HSN/SAC and active status.",
        "Customer receipts and vendor payments are linked back to the tailoring order so order history, balances and profit impact remain visible.",
        "Bank reconciliation now tracks open and reconciled statement lines with operator, date, reference, and remarks.",
        "Cheque logs now support an auditable lifecycle from issued/deposited through cleared, bounced, or cancelled with action timestamps.",
        "Fresh production installs continue to create one clean schema baseline from the current DbContext model instead of replaying historical branch migrations.",
        "Sales split payments now post separate settlement ledger and customer-credit rows for every collected payment line.",
        "Cash, bank, cheque, card, UPI, credit note, advance, store-credit and loyalty rows are routed to their own settlement ledgers instead of one mixed-payment ledger.",
        "Invoice payment rows now retain a structured payment-details JSON snapshot with mode, account, reference, gateway, cheque, card, UPI, and adjustment metadata.",
        "Duplicate use of the same advance receipt, credit note, store credit, or loyalty redemption is rejected before balances are changed.",
        "Nuxt font resolution now runs in local/no-provider mode so offline builds no longer depend on external font metadata.",
        "Owner and Admin users can move eligible cash records between Off Book Cash Vouchers and regular accounting vouchers without duplicating the amount.",
        "Every conversion retains source and destination numbers, direction, amount, reason, operator, and timestamp in an immutable audit history.",
        "Moving a regular cash voucher Off Book removes its journal postings and preserves the original source as an audit-only record.",
        "Sales Invoice creation now uses a stable full page with draft recovery, mobile customer lookup, contextual payments, rounded totals, and automatic print after save.",
        "Billing create, cancellation, return, and exchange transactions now run through the configured PostgreSQL retry execution strategy.",
        "B2B interstate GST is derived from supplier and customer GSTIN state codes, with IGST applied to interstate GST supplies.",
        "The sidebar footer again presents Status above Notifications as two full-width vertical actions.",
        "Inventory now includes a dedicated Stock Reports workspace for receipt-age indicators, configurable low-stock risk, weighted-average valuation, and ledger reconciliation.",
        "Stock report age bands cover 0-30, 31-60, 61-90, 91-180, and 180+ days, plus no-receipt-history and out-of-stock states.",
        "Stock Reports exposes Critical, Low, Watch, and Healthy risk bands, pending stock-accounting documents, searchable filters, and CSV export.",
        "Ledger quantity and average cost are compared with the operational stock projection so rebuild mismatches remain visible by product and store.",
        "Stock excess, shortage, write-off, and inter-store transfer documents now post balanced double-entry accounting at weighted-average cost.",
        "Store-wise Stock-in-Hand ledgers are created internally, with stock gains in Indirect Income and shortages/write-offs in Indirect Expenses.",
        "Stock Operations now includes a dedicated Write-off workflow with StoreCode/YYYYMM/WO/series numbering and linked movement and journal audit.",
        "Formal stock-operation documents now show Posted, Not Required, or Pending accounting status and their linked journal number.",
        "Status and Notifications are available as separate vertical actions in the sidebar footer.",
        "Stock adjustments, transfers, and physical counts now create formal header and item documents with immutable product, store, quantity, and value snapshots.",
        "Every posted stock-operation document links its movement-ledger rows and uses server-owned StoreCode/YYYYMM/ADJ, ST, or PHY numbering.",
        "The Stock Operations workspace now includes a searchable document register, operation filter, wide audit detail, and direct QR download.",
        "Universal document scanning now opens permitted stock-operation details by stable QR token or document number.",
        "Purchase returns now persist an immutable ITC reversal row for every returned item, including HSN and exact CGST, SGST, and IGST values.",
        "Purchase return details now reconcile the return header, item snapshots, stock movement, debit note, Input GST journal, and settlement state.",
        "Full purchase cancellations use the same item-level ITC reversal and reconciliation links as partial returns.",
        "The dashboard shell now has one header bar, one collapse control, one account menu, and notifications in the sidebar footer.",
        "Vendor debit notes can now be allocated across one or more outstanding purchase invoices without duplicating their accounting journal.",
        "Actual supplier refunds create receipt vouchers and balanced cash or bank entries linked to the vendor, return, debit note, journal, and bank transaction.",
        "Vendor settlements support adjustment-only, refund-only, and mixed workflows with server-owned StoreCode/YYYYMM/VSET/series numbering.",
        "The dedicated Vendor Settlements workspace shows open debit-note credit, invoice allocation, refund receipt, settlement history, and audit links.",
        "Non-cash vendor refunds require a receiving bank account, while generated refund vouchers use StoreCode/YYYYMM/VREF/series numbering and printable QR receipts.",
        "Purchase returns now generate colored A4 or A5 Purchase Return and Debit Note PDFs containing every returned item and exact GST reversal totals.",
        "Each purchase-return document carries a stable QR code that opens the permitted return detail from Document Scanner.",
        "New returns open their first print automatically, while print count, reprint state, and last print time remain auditable.",
        "The Purchase Return register now filters print state and provides direct print, reprint, download, and detail actions.",
        "Purchase returns now persist formal return headers and item-level product, HSN, GST, quantity, rate, vendor, and original-purchase snapshots.",
        "New purchase return numbers use a server-owned StoreCode/YYYYMM/PR/series sequence.",
        "Partial returns and full purchase cancellations now link stock movements and debit notes to the formal return document.",
        "The Purchase Return workspace now includes a searchable return register and snapshot detail view.",
        "Legacy stock-movement-only purchase returns remain included when calculating returnable quantities.",
        "One server-owned permission matrix now drives Admin, entry, edit, delete, and operational module authorization.",
        "The Access workspace displays the effective role matrix returned by the API.",
        "Store Manager retains store-module view and entry access without Admin, global edit, or delete rights.",
        "Dedicated HR and Payroll roles open only their assigned people module and land there after login.",
        "Automated role tests cover Owner, Admin, Power User, Accountant, Store Manager, Salesman, HR, and Payroll permissions.",
        "User activation, deactivation, role assignment, password administration, and deletion are now explicit audited workflows.",
        "Inactive users are denied at login and immediately blocked from authenticated API requests.",
        "Admin access is derived from the Admin role and can no longer be enabled through a separate user-facing flag.",
        "Administrative password resets use a dedicated endpoint and revoke outstanding reset tokens.",
        "The last active admin and the currently signed-in account are protected from accidental deactivation or deletion.",
        "The Stage 8A page audit queue is complete across operational, administration, maintenance, profile, and help workspaces.",
        "GST Returns now preserves local invoice and accounting dates and retains setup, draft, and review failures with direct retry actions.",
        "Profile, About Garmetix, Contact Us, and Help and FAQ now use consistent headers, loading states, and business-facing guidance.",
        "FAQ category filtering now uses a safe internal all-value sentinel instead of an invalid empty selector value.",
        "Company Setup and Roles and Users now use retryable registers, responsive tables and wide modal workspaces.",
        "Company, store-group and store dates preserve the selected local calendar date without UTC conversion.",
        "Company Onboarding and AF/SS Defaults now provide retained load failures, retry actions and responsive loading states.",
        "Internal migration, source-file and legacy implementation notes are no longer exposed on Admin business pages.",
        "Reports Center, GST Reports, Import Export, Audit Trail and Message Logs now use consistent retryable register states.",
        "Reports Center date defaults preserve the local calendar date instead of converting through UTC.",
        "Report, audit and data-operation failures remain visible with a direct retry action.",
        "Large report tables stay inside responsive scroll containers while actions wrap across smaller screens.",
        "Message Logs use compact operational panels and expandable technical details.",
        "Party and bank-account ledgers remain server-owned and synchronized by the accounting service.",
        "Salary payments now pre-calculate advance deductions, previous company dues and already-paid amounts.",
        "Printable business documents now carry stable permission-aware QR codes.",
        "Non-GST sale, purchase, stock, settlement and reporting now operate as an independent Off Book subsystem.",
        "Regular billing, purchase, stock operations, imports and dashboard totals explicitly exclude Off Book stock.",
        "Frontend, backend, npm package and .NET assembly versions are synchronized for every release."
    ];

    private static readonly AppContactDto[] ContactItems =
    [
        new("Business owner", "Amit Kumar", "person", "Primary business owner and authorization contact."),
        new("Email", "ameetkrsah@gmail.com", "email", "Use for account and support communication."),
        new("Location", "Dumka / Jamshedpur, Jharkhand, India", "location", "Business operating region."),
        new("Product", "Garmetix", "product", "Garment store management, billing, purchase, inventory, GST and controlled administration.")
    ];

    private static readonly AppFaqDto[] FaqItems =
    [
        new("How do I know which Garmetix version is running?", "Open About Garmetix and check the Version, Stage, Build Date and Build Code.", "Version"),
        new("Where do I create the first company?", "Use Admin > Company Onboarding. It creates the company, store group, store, initial users, employees and optional basic masters.", "Company"),
        new("Where do I prepare AF/SS default data?", "Use Admin > AF/SS Defaults, select the target company and profile, then apply the required defaults.", "Company"),
        new("Where can I see success or failure messages?", "Use Data > Message Logs. You can filter by source, level, success or failure, search text and date range.", "Logs"),
        new("How do I edit my own profile?", "Use Account > My Profile. You can change your name, username, email and password. Role, permissions and workspace assignment remain admin-controlled.", "Profile"),
        new("How do I prepare a GST return?", "Use GST > GST Returns, choose Load From Books, review the prepared values, save a draft if needed and confirm the return before export or filing.", "GST"),
        new("Where do I record Off Book Non-GST goods?", "Use Off Book > Non-GST Goods. Its sales, purchases, stock, settlements and PDFs are independent and do not create regular invoices, purchase bills, GST rows, ledgers, journals, vouchers or bank transactions.", "Non-GST Goods"),
        new("What details should I include when requesting support?", "Include the page name, operation performed, approximate time, visible message, and the Version and Build Code shown in About Garmetix.", "Support")
    ];
}
