export function useAttendance() {
  const api = useGarmetixApi()
  const today = (onDate?: string) => api.get<any>(`attendance/today${onDate ? `?onDate=${encodeURIComponent(onDate)}` : ''}`)
  const monthly = (params: { employeeId?: string, year?: number, month?: number } = {}) => {
    const query = new URLSearchParams()
    if (params.employeeId) query.set('employeeId', params.employeeId)
    if (params.year) query.set('year', String(params.year))
    if (params.month) query.set('month', String(params.month))
    const qs = query.toString()
    return api.get<any>(`attendance/monthly${qs ? `?${qs}` : ''}`)
  }
  const history = (employeeId: string) => api.get<any[]>(`attendance/employee/${employeeId}/history`)
  const manualPunch = (body: any) => api.create<any>('attendance/manual-punch', body)
  const regularization = () => api.list<any>('attendance/regularization')
  const createRegularization = (body: any) => api.create<any>('attendance/regularization', body)
  const approveRegularization = (id: string, remarks?: string) => api.create<any>(`attendance/regularization/${id}/approve`, { remarks })
  const rejectRegularization = (id: string, remarks?: string) => api.create<any>(`attendance/regularization/${id}/reject`, { remarks })
  const recalculate = (body: any) => api.create<any>('attendance/recalculate', body)
  const lockMonth = (body: any) => api.create<any>('attendance/lock-month', body)
  const payrollSummary = (year?: number, month?: number) => api.get<any>(`attendance/payroll-summary?year=${year || new Date().getFullYear()}&month=${month || new Date().getMonth() + 1}`)
  const payrollReview = (year?: number, month?: number) => api.get<any>(`attendance/payroll-review?year=${year || new Date().getFullYear()}&month=${month || new Date().getMonth() + 1}`)
  const rebuildPayrollReview = (body: any) => api.create<any>('attendance/payroll-review/rebuild', body)
  const markPayrollReview = (id: string, body: any) => api.create<any>(`attendance/payroll-review/${id}/mark-reviewed`, body)
  const salarySlipDrafts = (year?: number, month?: number) => api.get<any>(`attendance/salary-slip-drafts?year=${year || new Date().getFullYear()}&month=${month || new Date().getMonth() + 1}`)
  const rebuildSalarySlipDrafts = (body: any) => api.create<any>('attendance/salary-slip-drafts/rebuild', body)
  const markSalarySlipDraft = (id: string, body: any) => api.create<any>(`attendance/salary-slip-drafts/${id}/mark-ready`, body)
  const generateSalarySlipsFromDrafts = (body: any) => api.create<any>('attendance/salary-slip-drafts/generate-payslips', body)
  const salaryPaymentCandidates = (year?: number, month?: number) => api.get<any>(`attendance/salary-payment-candidates?year=${year || new Date().getFullYear()}&month=${month || new Date().getMonth() + 1}`)
  const generateSalaryPaymentsFromDrafts = (body: any) => api.create<any>('attendance/salary-payments/generate', body)
  const deviceBridgeStatus = () => api.get<any>('attendance/device-bridge/status')
  const deviceBridgeSimulatorHealth = () => api.get<any>('attendance/device-bridge/simulator/health')
  const deviceBridgeSimulatorCapture = (body: any = {}) => api.create<any>('attendance/device-bridge/simulator/capture', body)
  const deviceBridgeSimulatorIdentify = (body: any = {}) => api.create<any>('attendance/device-bridge/simulator/identify', body)
  const deviceBridgeSimulatorEnroll = (body: any = {}) => api.create<any>('attendance/device-bridge/simulator/enroll', body)
  const deviceBridgeExternalHealth = (body: any) => api.create<any>('attendance/device-bridge/external/health', body)
  const deviceBridgeExternalCapture = (body: any) => api.create<any>('attendance/device-bridge/external/capture', body)
  const deviceBridgeExternalIdentify = (body: any) => api.create<any>('attendance/device-bridge/external/identify', body)
  const deviceBridgeExternalEnroll = (body: any) => api.create<any>('attendance/device-bridge/external/enroll', body)
  const faceLivenessStatus = () => api.get<any>('attendance/face-liveness/status')
  const mobileKioskStatus = () => api.get<any>('attendance/mobile-kiosk/status')
  const mobileKioskOfflineContract = () => api.get<any>('attendance/mobile-kiosk/offline-contract')
  const mobileKioskRehearsal = () => api.get<any>('attendance/mobile-kiosk/rehearsal')
  const finalAcceptance = () => api.get<any>('attendance/final-acceptance')
  return { today, monthly, history, manualPunch, regularization, createRegularization, approveRegularization, rejectRegularization, recalculate, lockMonth, payrollSummary, payrollReview, rebuildPayrollReview, markPayrollReview, salarySlipDrafts, rebuildSalarySlipDrafts, markSalarySlipDraft, generateSalarySlipsFromDrafts, salaryPaymentCandidates, generateSalaryPaymentsFromDrafts, deviceBridgeStatus, deviceBridgeSimulatorHealth, deviceBridgeSimulatorCapture, deviceBridgeSimulatorIdentify, deviceBridgeSimulatorEnroll, deviceBridgeExternalHealth, deviceBridgeExternalCapture, deviceBridgeExternalIdentify, deviceBridgeExternalEnroll, faceLivenessStatus, mobileKioskStatus, mobileKioskOfflineContract, mobileKioskRehearsal, finalAcceptance }
}
