#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.production"
DOMAIN="${DOMAIN:-garmetix.aadwikafashion.in}"
PUBLIC_HTTPS_URL="${PUBLIC_HTTPS_URL:-https://${DOMAIN}}"

random_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "${1:-48}" | tr -d '\n'
  else
    date +%s%N | sha256sum | awk '{print $1}'
  fi
}

# shellcheck source=deploy/lib/env-file.sh
source "${ROOT_DIR}/deploy/lib/env-file.sh"

if [[ -f "$ENV_FILE" ]]; then
  normalize_env_file "$ENV_FILE"
fi

if [[ ! -f "$ENV_FILE" ]]; then
  cat >"$ENV_FILE" <<EOF2
POSTGRES_DB=garmetix
POSTGRES_USER=garmetix
POSTGRES_PASSWORD=$(random_secret 32)
POSTGRES_PORT=5432

JWT_ISSUER=Garmetix
JWT_AUDIENCE=GarmetixWeb
JWT_SIGNING_KEY=$(random_secret 64)

WEB_PORT=3000
API_PORT=5080
PUBLIC_DOMAIN=${DOMAIN}
PUBLIC_HTTPS_URL=${PUBLIC_HTTPS_URL}
NUXT_PUBLIC_SITE_URL=${PUBLIC_HTTPS_URL}
NUXT_PUBLIC_API_BASE=/api
NUXT_API_INTERNAL_BASE=http://api:5080/api
PASSWORD_RESET_FRONTEND_BASE_URL=${PUBLIC_HTTPS_URL}
CORS_ALLOWED_ORIGINS=${PUBLIC_HTTPS_URL}
ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
DATABASE_AUTO_MIGRATE=true
DATABASE_SCHEMA_BOOTSTRAP_MODE=FreshBaseline
RESET_DATABASE_ON_DEPLOY=false

EMAIL_ENABLED=false
EMAIL_HOST=
EMAIL_PORT=587
EMAIL_ENABLE_SSL=true
EMAIL_USERNAME=
EMAIL_PASSWORD=
EMAIL_FROM_EMAIL=no-reply@${DOMAIN#*.}
EMAIL_FROM_NAME=Garmetix
EMAIL_REPLY_TO_EMAIL=
EMAIL_TIMEOUT_SECONDS=30

LICENSE_ENFORCEMENT_ENABLED=false
LICENSE_REQUIRE_OPERATIONAL_APIS=true
LICENSE_PRODUCT_CODE=GARMETIX-WEB
LICENSE_MASTER_SECRET=$(random_secret 48)
LICENSE_DEFAULT_PLAN=Trial
LICENSE_DEFAULT_VALIDITY_DAYS=365
LICENSE_DEFAULT_MAX_STORES=1
LICENSE_DEFAULT_MAX_USERS=10
LICENSE_REQUIRED_MODULES=Billing,Inventory,Purchase,Accounting,GST,HR,Payroll

PAYROLL_AUTOMATION_ENABLED=true
PAYROLL_AUTOMATION_TIME_ZONE=Asia/Kolkata
PAYROLL_AUTOMATION_RUN_HOUR=2
PAYROLL_AUTOMATION_RUN_MINUTE=0
PAYROLL_AUTOMATION_RUN_ON_STARTUP=true

BACKUP_ENABLED=true
BACKUP_TIME_ZONE=Asia/Kolkata
BACKUP_RUN_HOUR=2
BACKUP_RUN_MINUTE=30
BACKUP_RUN_ON_STARTUP=false
BACKUP_RETENTION_COUNT=14

GOOGLE_DRIVE_BACKUP_ENABLED=false
GOOGLE_DRIVE_UPLOAD_ON_BACKUP=true
GOOGLE_DRIVE_FOLDER_ID=
GOOGLE_DRIVE_RETENTION_COUNT=30

GSTIN_LOOKUP_ENABLED=false
GSTIN_LOOKUP_BASE_URL=
GSTIN_LOOKUP_URL_TEMPLATE=
GSTIN_LOOKUP_API_KEY=
GSTIN_LOOKUP_API_KEY_HEADER=x-api-key
GSTIN_LOOKUP_SOURCE_NAME="Configured GSTIN Provider"

ORACLE_SYNC_ENABLED=false
ORACLE_SYNC_RUN_ON_STARTUP=false
ORACLE_SYNC_INTERVAL_SECONDS=300
ORACLE_SYNC_BATCH_SIZE=250
ORACLE_SYNC_CONNECTION_STRING=
ORACLE_SYNC_SCHEMA=
ORACLE_SYNC_TENANT_ID=garmetix-default
ORACLE_SYNC_SOURCE_APPLICATION=GarmetixWeb
ORACLE_SYNC_DIRECTION=PushToOracle
ORACLE_SYNC_CONFLICT_POLICY=ManualReview
ORACLE_SYNC_PULL_EXTERNAL_EVENTS=true
ORACLE_SYNC_APPLY_INBOUND_AUTOMATICALLY=false
ORACLE_SYNC_WALLET_DIRECTORY=
ORACLE_SYNC_TNS_ADMIN=
ORACLE_SYNC_CREATE_SCHEMA=true
ORACLE_SYNC_PUSH_DELETED_ROWS=true
ORACLE_SYNC_COMMAND_TIMEOUT_SECONDS=60
ORACLE_SYNC_ENTITY_NAMES=
ORACLE_SYNC_AUTO_APPLY_ENTITIES=
ORACLE_SYNC_TRUSTED_SOURCES=
ORACLE_SYNC_REQUIRE_TRUSTED_SOURCE_FOR_AUTO_APPLY=true
ORACLE_SYNC_AUTO_APPLY_BATCH_SIZE=50

DOCKER_LOG_MAX_SIZE=10m
DOCKER_LOG_MAX_FILE=5

CLOUDFLARE_TUNNEL_ID=
CLOUDFLARE_TUNNEL_TOKEN=

API_BASE_URL=${PUBLIC_HTTPS_URL}/api
GARMETIX_SMOKE_USER=
GARMETIX_SMOKE_PASSWORD=
EOF2
  normalize_env_file "$ENV_FILE"
  chmod_private_if_possible "$ENV_FILE"
fi

set_env_var "$ENV_FILE" PUBLIC_DOMAIN "$DOMAIN"
set_env_var "$ENV_FILE" PUBLIC_HTTPS_URL "$PUBLIC_HTTPS_URL"
set_env_var "$ENV_FILE" NUXT_PUBLIC_SITE_URL "$PUBLIC_HTTPS_URL"
set_env_var "$ENV_FILE" PASSWORD_RESET_FRONTEND_BASE_URL "$PUBLIC_HTTPS_URL"
set_env_var "$ENV_FILE" CORS_ALLOWED_ORIGINS "$PUBLIC_HTTPS_URL"
set_env_var "$ENV_FILE" API_BASE_URL "${PUBLIC_HTTPS_URL}/api"

if [[ -n "${CLOUDFLARE_TUNNEL_ID:-}" ]]; then
  set_env_var "$ENV_FILE" CLOUDFLARE_TUNNEL_ID "$CLOUDFLARE_TUNNEL_ID"
fi
if [[ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]]; then
  set_env_var "$ENV_FILE" CLOUDFLARE_TUNNEL_TOKEN "$CLOUDFLARE_TUNNEL_TOKEN"
fi

normalize_env_file "$ENV_FILE"
echo "Created/updated ${ENV_FILE}"
