<template>
  <section class="garmetix-page-stack">
    <div class="garmetix-dashboard-hero">
      <div class="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p class="garmetix-kicker"><UIcon name="i-lucide-file-signature" class="size-4" /> Accounting documents</p>
          <h2 class="garmetix-dashboard-title">Voucher Entry</h2>
          <p class="garmetix-dashboard-subtitle">
            Payment, receipt and expense vouchers with internal party-ledger and bank-ledger posting handled by the API. Accountants select the visible ledger only.
          </p>
        </div>
        <div class="flex flex-wrap gap-2">
          <UButton icon="i-lucide-plus" color="primary" variant="solid" @click="startCreate">New Voucher</UButton>
          <UButton icon="i-lucide-refresh-cw" color="neutral" variant="soft" :loading="loading" @click="refresh">Refresh</UButton>
          <UBadge color="success" variant="subtle">Writable parity</UBadge>
        </div>
      </div>
    </div>

    <UAlert v-if="error" color="warning" variant="subtle" icon="i-lucide-triangle-alert" :description="error" />
    <UAlert v-if="message" color="success" variant="subtle" icon="i-lucide-circle-check" :description="message" />

    <section class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <div v-for="card in cards" :key="card.label" class="garmetix-metric-card">
        <p class="garmetix-metric-label">{{ card.label }}</p>
        <p class="garmetix-metric-value">{{ card.value }}</p>
        <p class="garmetix-metric-caption">{{ card.detail }}</p>
      </div>
    </section>

    <section class="garmetix-section-card">
      <div class="mb-3 flex flex-col gap-2 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <h3 class="garmetix-panel-title">{{ formMode === 'edit' ? 'Edit Voucher' : 'New Voucher' }}</h3>
          <p class="garmetix-panel-subtitle">
            Voucher number is generated by store and month. Party ledger checks remain hidden and are resolved during save.
          </p>
        </div>
        <div class="flex flex-wrap gap-2">
          <UBadge color="neutral" variant="subtle">{{ selectedStoreLabel }}</UBadge>
          <UBadge :color="requiresBankAccount ? 'warning' : 'success'" variant="subtle">
            {{ requiresBankAccount ? 'Bank account required' : 'Cash voucher' }}
          </UBadge>
        </div>
      </div>

      <form class="grid gap-3 xl:grid-cols-12" @submit.prevent="saveVoucher">
        <div class="grid gap-3 sm:grid-cols-2 xl:col-span-3">
          <label class="space-y-1 text-sm">
            <span class="text-muted">Date</span>
            <UInput v-model="form.onDate" type="date" />
          </label>
          <label class="space-y-1 text-sm">
            <span class="text-muted">Type</span>
            <USelect v-model="form.voucherType" :items="voucherTypeSelectItems" />
          </label>
        </div>

        <div class="grid gap-3 sm:grid-cols-2 xl:col-span-5">
          <label class="space-y-1 text-sm">
            <span class="text-muted">Ledger</span>
            <USelect v-model="form.ledgerId" :items="ledgerSelectItems" placeholder="Select ledger" />
          </label>
          <label class="space-y-1 text-sm">
            <span class="text-muted">Party / Payee</span>
            <UInput v-model="form.partyName" placeholder="Party name" />
          </label>
        </div>

        <div class="grid gap-3 sm:grid-cols-2 xl:col-span-4">
          <label class="space-y-1 text-sm">
            <span class="text-muted">Issued By</span>
            <USelect v-model="form.employeeId" :items="employeeSelectItems" placeholder="Select employee" />
          </label>
          <label class="space-y-1 text-sm">
            <span class="text-muted">Amount</span>
            <UInput v-model="form.amount" type="number" min="0" step="0.01" placeholder="0.00" />
          </label>
        </div>

        <div class="grid gap-3 sm:grid-cols-2 xl:col-span-4">
          <label class="space-y-1 text-sm">
            <span class="text-muted">Payment Mode</span>
            <USelect v-model="form.paymentMode" :items="paymentModeSelectItems" />
          </label>
          <label class="space-y-1 text-sm">
            <span class="text-muted">{{ requiresBankAccount ? 'Bank Account' : 'Cash Slip Number' }}</span>
            <USelect
              v-if="requiresBankAccount"
              v-model="form.accountNumber"
              :items="bankAccountSelectItems"
              placeholder="Select bank account"
            />
            <UInput v-else v-model="form.slipNumber" placeholder="Optional cash slip" />
          </label>
        </div>

        <div class="grid gap-3 sm:grid-cols-2 xl:col-span-4">
          <label class="space-y-1 text-sm">
            <span class="text-muted">Particulars</span>
            <UInput v-model="form.particulars" placeholder="Voucher particulars" />
          </label>
          <label class="space-y-1 text-sm">
            <span class="text-muted">Payment Details</span>
            <UInput v-model="form.paymentDetails" placeholder="Txn, cheque, UPI or reference" />
          </label>
        </div>

        <label class="space-y-1 text-sm xl:col-span-4">
          <span class="text-muted">Remarks</span>
          <UTextarea v-model="form.remarks" :rows="3" placeholder="Internal remarks" />
        </label>

        <div class="flex flex-wrap items-end justify-end gap-2 xl:col-span-12">
          <UButton type="button" icon="i-lucide-rotate-ccw" color="neutral" variant="ghost" @click="startCreate">Clear</UButton>
          <UButton
            v-if="formMode === 'edit'"
            type="button"
            icon="i-lucide-trash-2"
            color="error"
            variant="soft"
            :loading="deleting"
            @click="deleteVoucher"
          >
            Delete
          </UButton>
          <UButton type="submit" icon="i-lucide-save" color="primary" :loading="saving">
            {{ formMode === 'edit' ? 'Update Voucher' : 'Save & Print' }}
          </UButton>
        </div>
      </form>
    </section>

    <section class="grid gap-4 xl:grid-cols-[minmax(0,1.6fr)_minmax(340px,0.8fr)]">
      <div class="garmetix-table-panel">
        <div class="mb-3 flex flex-col gap-2 xl:flex-row xl:items-center xl:justify-between">
          <div>
            <h3 class="garmetix-panel-title">Voucher List</h3>
            <p class="garmetix-panel-subtitle">{{ filteredVouchers.length }} row(s) shown</p>
          </div>
          <div class="flex flex-col gap-2 sm:flex-row">
            <USelect v-model="voucherTypeFilter" :items="voucherTypeFilterItems" class="sm:w-44" />
            <UInput v-model="search" icon="i-lucide-search" placeholder="Search vouchers" class="sm:w-72" />
          </div>
        </div>

        <div class="overflow-hidden rounded-lg border border-default">
          <div class="overflow-x-auto">
            <table class="w-full min-w-[1040px] text-left text-sm">
              <thead class="bg-muted/30 text-xs uppercase text-muted">
                <tr>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Date</th>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Voucher</th>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Type</th>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Party</th>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Ledger</th>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Mode</th>
                  <th class="whitespace-nowrap px-3 py-2 text-right font-medium">Amount</th>
                  <th class="whitespace-nowrap px-3 py-2 font-medium">Action</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-default">
                <tr v-if="filteredVouchers.length === 0">
                  <td colspan="8" class="px-3 py-8 text-center text-muted">No vouchers found.</td>
                </tr>
                <tr
                  v-for="voucher in filteredVouchers"
                  :key="voucherKey(voucher)"
                  class="bg-default/40"
                  :class="selectedVoucherId === readText(voucher, ['id'], '') ? 'outline outline-1 outline-primary/60' : ''"
                >
                  <td class="whitespace-nowrap px-3 py-2">{{ formatDate(voucher.onDate) }}</td>
                  <td class="px-3 py-2">
                    <p class="font-medium">{{ readText(voucher, ['voucherNumber']) }}</p>
                    <p class="text-xs text-muted">{{ readText(voucher, ['slipNumber'], 'No slip') }}</p>
                  </td>
                  <td class="whitespace-nowrap px-3 py-2">{{ voucherTypeLabel(voucher.voucherType) }}</td>
                  <td class="max-w-48 truncate px-3 py-2">{{ voucherPartyName(voucher) }}</td>
                  <td class="max-w-48 truncate px-3 py-2">{{ ledgerName(voucher.ledgerId) }}</td>
                  <td class="whitespace-nowrap px-3 py-2">{{ paymentModeLabel(voucher.paymentMode) }}</td>
                  <td class="whitespace-nowrap px-3 py-2 text-right font-medium">{{ formatIndianMoney(readNumber(voucher, ['amount'])) }}</td>
                  <td class="px-3 py-2">
                    <div class="flex flex-wrap gap-1">
                      <UButton icon="i-lucide-eye" size="xs" color="neutral" variant="soft" :loading="detailLoading && selectedVoucherId === readText(voucher, ['id'], '')" @click="selectVoucher(voucher)">
                        View
                      </UButton>
                      <UButton icon="i-lucide-pencil" size="xs" color="neutral" variant="ghost" @click="startEdit(voucher)">
                        Edit
                      </UButton>
                      <UButton icon="i-lucide-file-down" size="xs" color="primary" variant="ghost" :loading="downloadLoading === readText(voucher, ['id'], '')" @click="downloadVoucherFor(voucher, 'a5')">
                        PDF
                      </UButton>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <aside class="garmetix-detail-panel">
        <div class="flex items-start justify-between gap-3">
          <div>
            <h3 class="garmetix-panel-title">Voucher Details</h3>
            <p class="garmetix-panel-subtitle">{{ selectedVoucherNumber }}</p>
          </div>
          <UBadge :color="selectedVoucher ? 'success' : 'neutral'" variant="subtle">{{ selectedVoucher ? voucherTypeLabel(selectedVoucher.voucherType) : 'None' }}</UBadge>
        </div>

        <div v-if="selectedVoucher" class="mt-4 space-y-3">
          <dl class="grid gap-3 text-sm">
            <div v-for="item in selectedDetails" :key="item.label" class="border-b border-default pb-2">
              <dt class="text-xs text-muted">{{ item.label }}</dt>
              <dd class="mt-1 break-words font-medium">{{ item.value }}</dd>
            </div>
          </dl>

          <div class="flex flex-wrap gap-2 pt-1">
            <UButton icon="i-lucide-file-down" size="sm" color="primary" variant="soft" :loading="downloadLoading === 'a4'" @click="downloadVoucher('a4')">A4 PDF</UButton>
            <UButton icon="i-lucide-receipt-text" size="sm" color="neutral" variant="soft" :loading="downloadLoading === 'a5'" @click="downloadVoucher('a5')">A5 PDF</UButton>
            <UButton icon="i-lucide-printer" size="sm" color="neutral" variant="ghost" :loading="downloadLoading === 'reprint'" @click="downloadVoucher('reprint')">Reprint</UButton>
          </div>
        </div>

        <div v-else class="mt-8 text-center text-sm text-muted">
          Select a voucher to view details and PDF options.
        </div>
      </aside>
    </section>
  </section>
</template>

<script setup lang="ts">
import { formatIndianMoney } from '@garmetix/shared-utils'
import {
  formatDate,
  optionLabel,
  paymentModeOptions,
  readNumber,
  readText,
  toRows,
  type ApiRecord,
  useBooksApiClient,
  voucherTypeOptions
} from '../utils/books-api'

useHead({ title: 'Vouchers - Garmetix Books' })

type VoucherForm = {
  id: string
  voucherNumber: string
  onDate: string
  voucherType: number
  partyName: string
  particulars: string
  amount: number | string
  remarks: string
  slipNumber: string
  paymentMode: number
  paymentDetails: string
  ledgerId: string
  employeeId: string
  accountNumber: string
}

const { del, download, get, post, put } = useBooksApiClient()
const loading = ref(true)
const detailLoading = ref(false)
const saving = ref(false)
const deleting = ref(false)
const error = ref('')
const message = ref('')
const search = ref('')
const voucherTypeFilter = ref('all')
const selectedVoucherId = ref('')
const selectedVoucher = ref<ApiRecord | null>(null)
const downloadLoading = ref('')
const formMode = ref<'create' | 'edit'>('create')
const setupStatus = ref<ApiRecord | null>(null)
const vouchers = ref<ApiRecord[]>([])
const ledgers = ref<ApiRecord[]>([])
const parties = ref<ApiRecord[]>([])
const banks = ref<ApiRecord[]>([])
const bankAccounts = ref<ApiRecord[]>([])
const employees = ref<ApiRecord[]>([])
const companies = ref<ApiRecord[]>([])
const stores = ref<ApiRecord[]>([])

const form = reactive<VoucherForm>(emptyVoucher())

const voucherTypeSelectItems = voucherTypeOptions.map(item => ({ label: item.label, value: item.value }))
const paymentModeSelectItems = paymentModeOptions.map(item => ({ label: item.label, value: item.value }))
const voucherTypeFilterItems = [
  { label: 'All Types', value: 'all' },
  ...voucherTypeOptions.map(item => ({ label: item.label, value: item.label }))
]

const ledgerSelectItems = computed(() => ledgers.value
  .map(item => ({
    label: readText(item, ['name']),
    value: readText(item, ['id'], '')
  }))
  .filter(item => item.value))
const employeeSelectItems = computed(() => employees.value
  .map(item => ({
    label: readText(item, ['staffName', 'name', 'firstName']),
    value: readText(item, ['id'], '')
  }))
  .filter(item => item.value))
const bankAccountSelectItems = computed(() => bankAccounts.value
  .map(item => ({
    label: bankAccountLabel(readText(item, ['id'], '')),
    value: readText(item, ['id'], '')
  }))
  .filter(item => item.value))

const isCashPayment = computed(() => Number(form.paymentMode) === 0)
const requiresBankAccount = computed(() => !isCashPayment.value)
const selectedStoreLabel = computed(() => {
  const storeId = readText(setupStatus.value, ['storeId'], '') || readText(stores.value[0], ['id'], '')
  const store = stores.value.find(item => readText(item, ['id'], '') === storeId)
  return store ? readText(store, ['storeName', 'name'], 'Store') : 'Store not selected'
})

const ledgerName = (id: unknown) => readText(ledgers.value.find(item => readText(item, ['id'], '') === String(id ?? '')), ['name'])
const partyName = (id: unknown) => readText(parties.value.find(item => readText(item, ['id'], '') === String(id ?? '')), ['name'])
const employeeName = (id: unknown) => readText(employees.value.find(item => readText(item, ['id'], '') === String(id ?? '')), ['staffName', 'name', 'firstName'])
const bankName = (id: unknown) => readText(banks.value.find(item => readText(item, ['id'], '') === String(id ?? '')), ['name'])
const bankAccountLabel = (id: unknown) => {
  const account = bankAccounts.value.find(item => readText(item, ['id'], '') === String(id ?? ''))
  if (!account) return '-'
  return `${bankName(account.bankId)} - ${readText(account, ['accountHolderName'], 'Account')} - ${readText(account, ['accountNumber'])}`
}
const voucherTypeLabel = (value: unknown) => optionLabel(voucherTypeOptions, value)
const paymentModeLabel = (value: unknown) => optionLabel(paymentModeOptions, value)
const voucherPartyName = (voucher: ApiRecord) => readText(voucher, ['partyName'], partyName(voucher.partyId))
const voucherKey = (voucher: ApiRecord) => readText(voucher, ['id', 'voucherNumber'])

const cards = computed(() => {
  const paymentTotal = vouchers.value
    .filter(item => voucherTypeLabel(item.voucherType) === 'Payment')
    .reduce((sum, item) => sum + readNumber(item, ['amount']), 0)
  const receiptTotal = vouchers.value
    .filter(item => voucherTypeLabel(item.voucherType) === 'Receipt')
    .reduce((sum, item) => sum + readNumber(item, ['amount']), 0)
  const expenseTotal = vouchers.value
    .filter(item => voucherTypeLabel(item.voucherType) === 'Expense')
    .reduce((sum, item) => sum + readNumber(item, ['amount']), 0)

  return [
    { label: 'Vouchers', value: vouchers.value.length, detail: 'Accounting vouchers' },
    { label: 'Payments', value: formatIndianMoney(paymentTotal), detail: 'Payment voucher total' },
    { label: 'Receipts', value: formatIndianMoney(receiptTotal), detail: 'Receipt voucher total' },
    { label: 'Expenses', value: formatIndianMoney(expenseTotal), detail: 'Expense voucher total' }
  ]
})
const filteredVouchers = computed(() => {
  const term = search.value.trim().toLowerCase()
  return vouchers.value.filter(item => {
    const typeMatches = voucherTypeFilter.value === 'all' || voucherTypeLabel(item.voucherType) === voucherTypeFilter.value
    const textMatches = !term || [
      readText(item, ['voucherNumber']),
      readText(item, ['slipNumber']),
      readText(item, ['partyName']),
      readText(item, ['particulars']),
      readText(item, ['remarks']),
      ledgerName(item.ledgerId),
      paymentModeLabel(item.paymentMode)
    ].join(' ').toLowerCase().includes(term)
    return typeMatches && textMatches
  })
})
const selectedVoucherNumber = computed(() => selectedVoucher.value ? readText(selectedVoucher.value, ['voucherNumber']) : 'Select a voucher')
const selectedDetails = computed(() => {
  const voucher = selectedVoucher.value
  if (!voucher) return []
  return [
    { label: 'Date', value: formatDate(voucher.onDate) },
    { label: 'Party', value: voucherPartyName(voucher) },
    { label: 'Particulars', value: readText(voucher, ['particulars']) },
    { label: 'Amount', value: formatIndianMoney(readNumber(voucher, ['amount'])) },
    { label: 'Ledger', value: ledgerName(voucher.ledgerId) },
    { label: 'Payment Mode', value: paymentModeLabel(voucher.paymentMode) },
    { label: 'Payment Details', value: readText(voucher, ['paymentDetails']) },
    { label: 'Bank Account', value: bankAccountLabel(voucher.accountNumber) },
    { label: 'Issued By', value: employeeName(voucher.employeeId) },
    { label: 'Remarks', value: readText(voucher, ['remarks']) }
  ]
})

function emptyVoucher(): VoucherForm {
  return {
    id: '',
    voucherNumber: '',
    onDate: localDateValue(),
    voucherType: 0,
    partyName: '',
    particulars: '',
    amount: 0,
    remarks: '',
    slipNumber: '',
    paymentMode: 0,
    paymentDetails: '',
    ledgerId: '',
    employeeId: '',
    accountNumber: ''
  }
}

function localDateValue(value: unknown = new Date()) {
  if (typeof value === 'string' && /^\d{4}-\d{2}-\d{2}/.test(value)) return value.slice(0, 10)
  const date = value instanceof Date ? value : new Date(String(value || new Date()))
  if (Number.isNaN(date.getTime())) return localDateValue(new Date())
  const offsetMs = date.getTimezoneOffset() * 60_000
  return new Date(date.getTime() - offsetMs).toISOString().slice(0, 10)
}

function accountingDateTimeForApi(value: string) {
  return `${localDateValue(value)}T00:00:00`
}

function startCreate() {
  formMode.value = 'create'
  Object.assign(form, emptyVoucher())
  form.ledgerId = ledgerSelectItems.value.find(item => item.label === 'Cash In Hand')?.value || ledgerSelectItems.value[0]?.value || ''
  form.employeeId = employeeSelectItems.value[0]?.value || ''
  form.accountNumber = bankAccountSelectItems.value[0]?.value || ''
  message.value = ''
  error.value = ''
}

function startEdit(voucher: ApiRecord) {
  formMode.value = 'edit'
  Object.assign(form, {
    id: readText(voucher, ['id'], ''),
    voucherNumber: readText(voucher, ['voucherNumber'], ''),
    onDate: localDateValue(voucher.onDate),
    voucherType: Number(voucher.voucherType ?? 0),
    partyName: voucherPartyName(voucher),
    particulars: readText(voucher, ['particulars'], ''),
    amount: readNumber(voucher, ['amount']),
    remarks: readText(voucher, ['remarks'], ''),
    slipNumber: readText(voucher, ['slipNumber'], ''),
    paymentMode: Number(voucher.paymentMode ?? 0),
    paymentDetails: readText(voucher, ['paymentDetails'], ''),
    ledgerId: readText(voucher, ['ledgerId'], ''),
    employeeId: readText(voucher, ['employeeId'], ''),
    accountNumber: readText(voucher, ['accountNumber'], '')
  })
  selectVoucher(voucher)
  message.value = ''
  error.value = ''
}

function setupIds() {
  const selectedStoreId = readText(setupStatus.value, ['storeId'], '') || readText(stores.value[0], ['id'], '')
  const selectedStore = stores.value.find(item => readText(item, ['id'], '') === selectedStoreId) ?? stores.value[0]
  const companyId = readText(setupStatus.value, ['companyId'], '') || readText(selectedStore, ['companyId'], '') || readText(companies.value[0], ['id'], '')
  const storeGroupId = readText(setupStatus.value, ['storeGroupId'], '') || readText(selectedStore, ['storeGroupId'], '')
  const storeId = selectedStoreId || readText(selectedStore, ['id'], '')

  if (!companyId || !storeGroupId || !storeId) throw new Error('Run quick setup before saving vouchers.')
  return { companyId, storeGroupId, storeId }
}

function buildPayload() {
  const { companyId, storeGroupId, storeId } = setupIds()
  const partyLedger = parties.value.find(item => readText(item, ['ledgerId'], '') === form.ledgerId)
  const partyNameFromLedger = readText(partyLedger, ['name'], '')
  const resolvedPartyName = String(partyNameFromLedger || form.partyName || '').trim()

  if (!form.ledgerId) throw new Error('Select ledger before saving voucher.')
  if (!resolvedPartyName) throw new Error('Enter party name before saving voucher.')
  if (!form.employeeId) throw new Error('Select who issued this voucher.')
  if (Number(form.amount || 0) <= 0) throw new Error('Enter voucher amount greater than zero.')
  if (requiresBankAccount.value && !form.accountNumber) throw new Error('Select bank account for non-cash voucher.')

  return {
    id: formMode.value === 'edit' && form.id ? form.id : null,
    voucherNumber: formMode.value === 'edit' ? String(form.voucherNumber || '').trim() : '',
    onDate: accountingDateTimeForApi(form.onDate),
    voucherType: Number(form.voucherType),
    partyName: resolvedPartyName,
    particulars: String(form.particulars || '').trim(),
    amount: Number(form.amount || 0),
    remarks: String(form.remarks || '').trim() || null,
    slipNumber: isCashPayment.value ? String(form.slipNumber || '').trim() || null : 'NA',
    paymentMode: Number(form.paymentMode),
    paymentDetails: String(form.paymentDetails || '').trim() || null,
    isParty: false,
    partyId: null,
    ledgerId: form.ledgerId,
    employeeId: form.employeeId,
    accountNumber: requiresBankAccount.value ? form.accountNumber : null,
    companyId,
    storeGroupId,
    storeId
  }
}

async function refresh() {
  loading.value = true
  error.value = ''
  try {
    const [setupData, companyData, storeData, voucherData, ledgerData, partyData, bankData, bankAccountData, employeeData] = await Promise.allSettled([
      get<unknown>('setup/status'),
      get<unknown>('companies'),
      get<unknown>('stores'),
      get<unknown>('vouchers'),
      get<unknown>('ledgers'),
      get<unknown>('parties'),
      get<unknown>('banks'),
      get<unknown>('bank-accounts'),
      get<unknown>('employees')
    ])

    if (setupData.status === 'fulfilled' && setupData.value && typeof setupData.value === 'object') setupStatus.value = setupData.value as ApiRecord
    if (companyData.status === 'fulfilled') companies.value = toRows(companyData.value)
    if (storeData.status === 'fulfilled') stores.value = toRows(storeData.value)
    if (voucherData.status === 'fulfilled') vouchers.value = toRows(voucherData.value)
    if (ledgerData.status === 'fulfilled') ledgers.value = toRows(ledgerData.value)
    if (partyData.status === 'fulfilled') parties.value = toRows(partyData.value)
    if (bankData.status === 'fulfilled') banks.value = toRows(bankData.value)
    if (bankAccountData.status === 'fulfilled') bankAccounts.value = toRows(bankAccountData.value)
    if (employeeData.status === 'fulfilled') employees.value = toRows(employeeData.value)

    if (!ledgers.value.length || !parties.value.length || !bankAccounts.value.length) {
      await post<unknown>('setup/accounting-defaults', {})
      const [refreshedLedgers, refreshedParties, refreshedBankAccounts] = await Promise.all([
        get<unknown>('ledgers'),
        get<unknown>('parties'),
        get<unknown>('bank-accounts')
      ])
      ledgers.value = toRows(refreshedLedgers)
      parties.value = toRows(refreshedParties)
      bankAccounts.value = toRows(refreshedBankAccounts)
    }

    if (!form.ledgerId || !form.employeeId) startCreate()

    if (!selectedVoucherId.value && vouchers.value.length > 0) {
      await selectVoucher(vouchers.value[0])
    } else if (selectedVoucherId.value && !vouchers.value.some(item => readText(item, ['id'], '') === selectedVoucherId.value)) {
      selectedVoucherId.value = ''
      selectedVoucher.value = null
    }

    const failed = [setupData, companyData, storeData, voucherData, ledgerData, partyData, bankData, bankAccountData, employeeData].filter(item => item.status === 'rejected').length
    if (failed) error.value = `${failed} voucher reference request(s) could not be loaded.`
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : 'Unable to load vouchers.'
  } finally {
    loading.value = false
  }
}

async function selectVoucher(voucher: ApiRecord) {
  const id = readText(voucher, ['id'], '')
  selectedVoucherId.value = id
  selectedVoucher.value = voucher
  if (!id) return

  detailLoading.value = true
  try {
    const detail = await get<unknown>(`vouchers/${id}`)
    if (detail && typeof detail === 'object') selectedVoucher.value = detail as ApiRecord
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : 'Unable to load voucher details.'
  } finally {
    detailLoading.value = false
  }
}

async function saveVoucher() {
  saving.value = true
  error.value = ''
  message.value = ''
  try {
    const payload = buildPayload()
    const saved = formMode.value === 'edit' && form.id
      ? await put<ApiRecord>(`vouchers/${form.id}`, payload)
      : await post<ApiRecord>('vouchers', payload)

    const savedId = readText(saved, ['id'], form.id)
    message.value = formMode.value === 'edit' ? 'Voucher updated.' : 'Voucher saved. PDF download started.'
    await refresh()
    if (savedId) {
      const savedRow = vouchers.value.find(item => readText(item, ['id'], '') === savedId) ?? saved
      await selectVoucher(savedRow)
      if (formMode.value === 'create') await downloadVoucherFor(savedRow, 'a5')
      startEdit(savedRow)
    }
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : 'Unable to save voucher.'
  } finally {
    saving.value = false
  }
}

async function deleteVoucher() {
  if (!form.id) return
  if (!window.confirm('Delete this voucher? This will reverse posted accounting entries through the API.')) return

  deleting.value = true
  error.value = ''
  message.value = ''
  try {
    await del<unknown>(`vouchers/${form.id}`)
    message.value = 'Voucher deleted.'
    selectedVoucherId.value = ''
    selectedVoucher.value = null
    startCreate()
    await refresh()
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : 'Unable to delete voucher.'
  } finally {
    deleting.value = false
  }
}

async function downloadVoucher(mode: 'a4' | 'a5' | 'reprint') {
  const id = selectedVoucherId.value
  if (!id) return
  await downloadVoucherById(id, selectedVoucherNumber.value, mode)
}

async function downloadVoucherFor(voucher: ApiRecord, mode: 'a4' | 'a5' | 'reprint') {
  const id = readText(voucher, ['id'], '')
  if (!id) return
  await downloadVoucherById(id, readText(voucher, ['voucherNumber'], 'voucher'), mode)
}

async function downloadVoucherById(id: string, voucherNumber: string, mode: 'a4' | 'a5' | 'reprint') {
  downloadLoading.value = mode === 'a5' ? id : mode
  error.value = ''
  try {
    const query = mode === 'a5'
      ? { format: 'a5-one', reprint: false, signatures: true }
      : mode === 'reprint'
        ? { format: 'a5-one', reprint: true, signatures: true }
        : { format: 'a4-two', reprint: false, signatures: true }
    await download(`vouchers/${id}/pdf`, query, `${voucherNumber}.pdf`)
  } catch (caught) {
    error.value = caught instanceof Error ? caught.message : 'Unable to download voucher PDF.'
  } finally {
    downloadLoading.value = ''
  }
}

watch(() => form.ledgerId, (ledgerId) => {
  const party = parties.value.find(item => readText(item, ['ledgerId'], '') === ledgerId)
  if (party) form.partyName = readText(party, ['name'], form.partyName)
})

watch(() => form.paymentMode, () => {
  if (requiresBankAccount.value && !form.accountNumber) form.accountNumber = bankAccountSelectItems.value[0]?.value || ''
  if (isCashPayment.value) form.accountNumber = ''
})

onMounted(refresh)
</script>
