using System.Globalization;
using System.Text;
using Garmetix.Api.ProductLookup;
using Garmetix.Models.DayOperations;

namespace Garmetix.Api.Accounting;

public sealed record PettyCashTransactionLine(string Category, string Type, string Reference, string Particulars, decimal Amount);

public static class PettyCashPdfDocument
{
    private const double Width = 595.28;
    private const double Height = 419.53;

    public static byte[] Build(PettyCashSheet sheet, string companyName, string storeName, IReadOnlyList<PettyCashTransactionLine>? transactionLines = null)
    {
        var canvas = new Canvas(Height);
        const double left = 18;
        const double top = 16;
        const double bodyWidth = Width - 36;
        canvas.Stroke(left, top, bodyWidth, Height - 32, 0.8, 0.32, 0.38, 0.44);
        canvas.Fill(left, top, bodyWidth, 52, 0.02, 0.09, 0.16);
        canvas.Fill(left, top + 52, bodyWidth, 3, 0.02, 0.70, 0.64);
        canvas.Text(companyName, left + 12, top + 9, 15, true, 1, 1, 1);
        canvas.Text($"{storeName} | DAILY PETTY CASH SHEET", left + 12, top + 29, 8, false, 0.82, 0.88, 0.94);
        canvas.Text(sheet.OnDate.ToString("dd MMM yyyy", CultureInfo.InvariantCulture), left + bodyWidth - 150, top + 13, 10, true, 1, 1, 1);
        canvas.Qr(DocumentCodeService.Create(DocumentCodeService.PettyCash, sheet.Id), left + bodyWidth - 45, top + 5, 40);

        var tableTop = top + 68;
        var columnGap = 12d;
        var columnWidth = (bodyWidth - 24 - columnGap) / 2;
        DrawSection(canvas, left + 8, tableTop, columnWidth, "CASH IN / RECEIPTS",
        [
            ("Opening balance", sheet.OpeningBalance),
            ("Cash sales", sheet.Sales),
            ("Receipts", sheet.Receipts),
            ("Due receipts", sheet.DueReceipts),
            ("Bank withdrawal", sheet.BankWithdrawal)
        ]);
        DrawSection(canvas, left + 8 + columnWidth + columnGap, tableTop, columnWidth, "CASH OUT / PAYMENTS",
        [
            ("Expenses", sheet.Expenses),
            ("Payments", sheet.Payments),
            ("Customer due", sheet.CustomerDue),
            ("Bank deposit", sheet.BankDeposit),
            ("Non-cash sales", sheet.NonCashSale)
        ]);

        var totalIn = sheet.OpeningBalance + sheet.Sales + sheet.Receipts + sheet.DueReceipts + sheet.BankWithdrawal;
        var totalOut = sheet.Expenses + sheet.Payments + sheet.CustomerDue + sheet.BankDeposit + sheet.NonCashSale;
        var summaryTop = tableTop + 183;
        canvas.Fill(left + 8, summaryTop, bodyWidth - 16, 48, 0.91, 0.98, 0.97);
        canvas.Stroke(left + 8, summaryTop, bodyWidth - 16, 48, 0.4, 0.57, 0.66, 0.65);
        canvas.Text($"Total cash in: INR {totalIn:N2}", left + 18, summaryTop + 10, 8, true);
        canvas.Text($"Total cash out: INR {totalOut:N2}", left + 18, summaryTop + 27, 8, true);
        canvas.Text("CLOSING CASH IN HAND", left + bodyWidth - 210, summaryTop + 9, 8, true, 0.04, 0.42, 0.38);
        canvas.Text($"INR {sheet.CashInHand:N2}", left + bodyWidth - 210, summaryTop + 25, 13, true, 0.02, 0.31, 0.29);

        var signatureTop = Height - 58;
        var labels = new[] { "Prepared by", "Verified by", "Owner / Manager" };
        var signatureWidth = (bodyWidth - 30) / labels.Length;
        for (var index = 0; index < labels.Length; index++)
        {
            var x = left + 15 + signatureWidth * index;
            canvas.Line(x + 8, signatureTop, x + signatureWidth - 8, signatureTop);
            canvas.Centered(labels[index], x, signatureTop + 7, signatureWidth, 7);
        }
        canvas.Centered("Generated by Garmetix | Scan QR to open the saved sheet", left, Height - 25, bodyWidth, 6.8);

        if (transactionLines is { Count: > 0 })
        {
            var detailPages = DrawTransactionDetailPages(transactionLines, companyName, storeName, sheet.OnDate);
            return BuildPdf([canvas.Content, .. detailPages]);
        }

        return BuildPdf(canvas.Content);
    }

    private static IReadOnlyList<string> DrawTransactionDetailPages(IReadOnlyList<PettyCashTransactionLine> lines, string companyName, string storeName, DateTime onDate)
    {
        const int rowsPerPage = 12;
        var pages = new List<string>();
        var pageCount = Math.Max(1, (int)Math.Ceiling(lines.Count / (double)rowsPerPage));
        var income = lines.Where(line => line.Category == "Income").Sum(line => line.Amount);
        var expense = lines.Where(line => line.Category == "Expense").Sum(line => line.Amount);
        var adjustment = lines.Where(line => line.Category == "Adjustment").Sum(line => line.Amount);

        for (var pageNumber = 0; pageNumber < pageCount; pageNumber++)
        {
            var pageLines = lines
                .Skip(pageNumber * rowsPerPage)
                .Take(rowsPerPage)
                .ToList();
            var canvas = new Canvas(Height);
            DrawTransactionDetailPage(canvas, pageLines, companyName, storeName, onDate, pageNumber + 1, pageCount, income, expense, adjustment);
            pages.Add(canvas.Content);
        }

        return pages;
    }

    private static void DrawTransactionDetailPage(
        Canvas canvas,
        IReadOnlyList<PettyCashTransactionLine> lines,
        string companyName,
        string storeName,
        DateTime onDate,
        int pageNumber,
        int pageCount,
        decimal income,
        decimal expense,
        decimal adjustment)
    {
        const double left = 18;
        const double top = 16;
        const double bodyWidth = Width - 36;
        canvas.Stroke(left, top, bodyWidth, Height - 32, 0.8, 0.32, 0.38, 0.44);
        canvas.Fill(left, top, bodyWidth, 40, 0.02, 0.09, 0.16);
        canvas.Text(companyName, left + 12, top + 8, 13, true, 1, 1, 1);
        canvas.Text($"{storeName} | BOOK TRANSACTION DETAILS | {onDate:dd MMM yyyy}", left + 12, top + 26, 7.5, false, 0.82, 0.88, 0.94);
        canvas.Right($"Page {pageNumber} of {pageCount}", left + bodyWidth - 12, top + 16, 7.2, true);

        var y = top + 54;
        canvas.Fill(left + 8, y, bodyWidth - 16, 22, 0.91, 0.98, 0.97);
        canvas.Text("Category", left + 14, y + 7, 7.2, true);
        canvas.Text("Type", left + 85, y + 7, 7.2, true);
        canvas.Text("Reference", left + 185, y + 7, 7.2, true);
        canvas.Text("Particulars", left + 275, y + 7, 7.2, true);
        canvas.Right("Amount", left + bodyWidth - 18, y + 7, 7.2, true);
        y += 22;

        foreach (var line in lines)
        {
            canvas.Stroke(left + 8, y, bodyWidth - 16, 22, 0.18, 0.82, 0.85, 0.88);
            canvas.Text(line.Category, left + 14, y + 7, 6.6);
            canvas.Text(line.Type, left + 85, y + 7, 6.6);
            canvas.Text(line.Reference, left + 185, y + 7, 6.6);
            canvas.Text(line.Particulars, left + 275, y + 7, 6.4);
            canvas.Right(line.Amount.ToString("N2", CultureInfo.InvariantCulture), left + bodyWidth - 18, y + 7, 6.6, true);
            y += 22;
        }

        var footerTitle = pageNumber == pageCount
            ? "Transaction totals"
            : "Continued on next A5 detail page";
        canvas.Fill(left + 8, Height - 60, bodyWidth - 16, 34, pageNumber == pageCount ? 0.95 : 0.91, pageNumber == pageCount ? 0.97 : 0.98, pageNumber == pageCount ? 0.98 : 0.97);
        canvas.Text(footerTitle, left + 18, Height - 51, 7.2, true, 0.04, 0.42, 0.38);
        canvas.Text($"Income: INR {income:N2}", left + 18, Height - 38, 7.2, true);
        canvas.Text($"Expense: INR {expense:N2}", left + 180, Height - 38, 7.2, true);
        canvas.Text($"Adjustments: INR {adjustment:N2}", left + 350, Height - 38, 7.2, true);
    }

    private static void DrawSection(Canvas canvas, double left, double top, double width, string title, IReadOnlyList<(string, decimal)> rows)
    {
        canvas.Fill(left, top, width, 25, 0.02, 0.09, 0.16);
        canvas.Text(title, left + 8, top + 8, 8, true, 1, 1, 1);
        var y = top + 25;
        foreach (var row in rows)
        {
            canvas.Stroke(left, y, width, 27, 0.25, 0.82, 0.85, 0.88);
            canvas.Text(row.Item1, left + 8, y + 9, 7.5);
            canvas.Right(row.Item2.ToString("N2", CultureInfo.InvariantCulture), left + width - 8, y + 9, 7.5, true);
            y += 27;
        }
        canvas.Fill(left, y, width, 28, 0.95, 0.97, 0.98);
        canvas.Text("SECTION TOTAL", left + 8, y + 9, 7.5, true);
        canvas.Right(rows.Sum(row => row.Item2).ToString("N2", CultureInfo.InvariantCulture), left + width - 8, y + 9, 7.5, true);
    }

private static byte[] BuildPdf(string content) => BuildPdf([content]);

private static byte[] BuildPdf(IReadOnlyList<string> contents)
{
    var pageCount = contents.Count;
    var font1Id = 3 + pageCount * 2;
    var font2Id = font1Id + 1;
    var kids = string.Join(" ", Enumerable.Range(0, pageCount).Select(index => $"{3 + index * 2} 0 R"));
    var objects = new List<string>
    {
        "<< /Type /Catalog /Pages 2 0 R >>",
        $"<< /Type /Pages /Kids [{kids}] /Count {pageCount} >>"
    };

    for (var index = 0; index < pageCount; index++)
    {
        var pageObjId = 3 + index * 2;
        var contentObjId = pageObjId + 1;
        var streamBytes = Encoding.ASCII.GetBytes(contents[index]);
        objects.Add($"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 {F(Width)} {F(Height)}] /Resources << /Font << /F1 {font1Id} 0 R /F2 {font2Id} 0 R >> >> /Contents {contentObjId} 0 R >>");
        objects.Add($"<< /Length {streamBytes.Length} >>\nstream\n{contents[index]}endstream");
    }

    objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>");
    objects.Add("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>");

    using var output = new MemoryStream();
    Write(output, "%PDF-1.4\n%Garmetix\n");
    var offsets = new List<long> { 0 };
    for (var index = 0; index < objects.Count; index++)
    {
        offsets.Add(output.Position);
        Write(output, $"{index + 1} 0 obj\n{objects[index]}\nendobj\n");
    }
    var xref = output.Position;
    Write(output, $"xref\n0 {objects.Count + 1}\n0000000000 65535 f \n");
    foreach (var offset in offsets.Skip(1)) Write(output, $"{offset:D10} 00000 n \n");
    Write(output, $"trailer\n<< /Size {objects.Count + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF");
    return output.ToArray();
}

    private static void Write(Stream stream, string value)
    {
        var bytes = Encoding.ASCII.GetBytes(value);
        stream.Write(bytes);
    }

    private static string F(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);

    private sealed class Canvas(double pageHeight)
    {
        private readonly StringBuilder builder = new();
        public string Content => builder.ToString();
        public void Text(string value, double x, double top, double size, bool bold = false, double r = 0.08, double g = 0.12, double b = 0.18)
            => builder.Append(CultureInfo.InvariantCulture, $"BT /{(bold ? "F2" : "F1")} {F(size)} Tf {F(r)} {F(g)} {F(b)} rg 1 0 0 1 {F(x)} {F(pageHeight - top - size)} Tm ({Escape(value)}) Tj ET\n");
        public void Right(string value, double right, double top, double size, bool bold = false)
            => Text(value, right - Sanitize(value).Length * size * (bold ? 0.55 : 0.5), top, size, bold);
        public void Centered(string value, double left, double top, double width, double size)
            => Text(value, left + Math.Max(0, (width - Sanitize(value).Length * size * 0.5) / 2), top, size);
        public void Fill(double left, double top, double width, double height, double r, double g, double b)
            => builder.Append(CultureInfo.InvariantCulture, $"{F(r)} {F(g)} {F(b)} rg {F(left)} {F(pageHeight - top - height)} {F(width)} {F(height)} re f\n");
        public void Stroke(double left, double top, double width, double height, double lineWidth, double r, double g, double b)
            => builder.Append(CultureInfo.InvariantCulture, $"{F(r)} {F(g)} {F(b)} RG {F(lineWidth)} w {F(left)} {F(pageHeight - top - height)} {F(width)} {F(height)} re S\n");
        public void Line(double x1, double top1, double x2, double top2)
            => builder.Append(CultureInfo.InvariantCulture, $"0.45 0.49 0.54 RG 0.5 w {F(x1)} {F(pageHeight - top1)} m {F(x2)} {F(pageHeight - top2)} l S\n");
        public void Qr(string payload, double left, double top, double size)
            => DocumentCodeService.AppendPdfCommands(builder, pageHeight, left, top, size, payload);
        private static string Escape(string value) => Sanitize(value).Replace("\\", "\\\\").Replace("(", "\\(").Replace(")", "\\)");
        private static string Sanitize(string? value) => new((value ?? string.Empty).Select(character => character is >= ' ' and <= '~' ? character : '?').ToArray());
    }
}
